### ISSUE TITLE
snlc_fit error pointing to README

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1002]
in /project2/rkessler/SURVEYS/DES/ROOT/analysis_photoIa_5yr/test_Trest
I was trying to run the code: ./test_snlcfit.cmd and get this strange error

```
  ########################################################
    INIT_SNCID_LISTS
  ########################################################

    Store     41 integer CIDs from SNCID_LIST
    IGNORE    2 CIDs from SNCID_IGNORE
    IGNORE    0 CIDs from SNCCID_IGNORE

  init_SNDATA_GLOBAL:

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by get_PARSE_WORD
   iwd=10 exceeds NWD_STORE=10
   Check FILENAME = '/project2/rkessler/SURVEYS/DES/USERS/sanchezb/test_makedatafiles/lcmerge_des_smp/DES5YR_SMP/DES5YR_SMP.README'
```

**Comment by RickKessler** [comment]
this bug showed up because I had accidentally left the makeFile in debug mode ... which was a good thing. This bug is from insufficient memory allocation to a local string for reading keys in check_file_docana. After fixing this bug, found and fixed another bug in recently developed SNHOST_CONFUSION subroutine.
