### ISSUE TITLE
FATAL ERROR ABORT called by check_SNDATA_HOSTGAL_SNSEP

### ISSUE THREAD

**Issue by jpierel14** [RickKessler/SNANA#1022]
Get this error when running a strong lensing simulation (`$SNANA_DEBUG/Justin/host_sep_issue`), reproducible with `sh REPRODUCE_CMD.sh`

**Comment by RickKessler** [comment]
There are two issues here. First, I fixed a bug so that a lens galaxy can be selected if logMass is not available to use as a weight. The other issue is that there is no Sersic profile in the HOSTLIB, and this messes up coordinates. I therefore turned off the SN-host coordinate sanity check if there is no Sersic profile.
