### ISSUE TITLE
FLUXERRMODEL_SIM not working

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1063]
Folder: /project2/rkessler/PRODUCTS/SNANA_DEBUG/mvincenzi/DESSIMBIAS_4D_P21_NEWERR/LOGS
Run FAIL.CMD to repeat the error

The error seem to be related with the new fluxerror map:
`FLUXERRMODEL_FILE: $DES_ROOT/simlibs/FLUXERRMODEL_maps/FLUXERRMODEL_SIM.DAT`

**Comment by maria-vincenzi** [comment]
If I comment out the line:
REDCOV: griz:0.4
in $DES_ROOT/simlibs/FLUXERRMODEL_maps/FLUXERRMODEL_SIM.DAT
everything works... so it's a problem with REDCOV

**Comment by RickKessler** [comment]
The underlying bug is that the sim was writing the cumulative field list for each epoch, instead of the field for each epoch. For for field overlaps, when field list becomes e.g.,  C2+C3, this C2+C3 string was written as the field epoch instead of C3. The C2+C3 field was not recognized in any REDCOV map and thus returned an error scale of 1, which resulted in COV matrix elements of zero ... which is not pos definite. 

Anticipating a related bug in the future, if the FLUXERRMODEL_FILE includes error scales that are exactly 1.000, the sim code replaces 1.00 with 1.01 to avoid GSL error "matrix not pos definite".
