### ISSUE TITLE
fieldGroup and fieldlist bug

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1075]
in folder `/project2/rkessler/PRODUCTS/SNANA_DEBUG/mvincenzi/fieldGroup_fieldlist`
I prepared three jobs to replicate the errors

When running the DES analysis using:
`fieldlist=X3,VOID fieldGroup_biascor=X3`
or 
`fieldlist=X1,X2,VOID fieldGroup_biascor=X1+X2`
I get the error
```
 FATAL ERROR ABORT called by sort_IDSAMPLE_biasCor
   Found DES events NOT in FIELDGROUP
   Define all fields in fieldgroup_biascor key.
```

Strangely, I don't get the same error if, for example, I run the command specifiying:
`fieldlist=C3,VOID fieldGroup_biascor=C3`

**Comment by RickKessler** [comment]
This is a subtle refactor bug from last week in which prepare_IDSAMPLE is called before applying cuts (instead of after). The problem is that field list cut is not yet applied, which messes up fieldgroup_biasCor logic. The fix is to apply the field list cut (see select_FIELD function) when determining field groups for IDSAMPLEs.
