### ISSUE TITLE
validating wfit and cosmoSIS

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1082]
We find strange results from wfit
We tried running the test on the Pantheon+ dataset.
Pantheon+ data: `https://raw.githubusercontent.com/PantheonPlusSH0ES/DataRelease/main/Pantheon%2B_Data/4_DISTANCES_AND_COVAR/Pantheon%2BSH0ES.dat`
Pantheon+ cov matrix: `https://raw.githubusercontent.com/PantheonPlusSH0ES/DataRelease/main/Pantheon%2B_Data/4_DISTANCES_AND_COVAR/Pantheon%2BSH0ES_STAT%2BSYS.cov`

Pantheon+ results using CosmoSIS: `https://github.com/PantheonPlusSH0ES/DataRelease/tree/main/Pantheon%2B_Data/5_COSMOLOGY/chains/Pantheon%2BSH0ES`
Ayan is gonna post where the results with `wfit` are.
We know that there are some differences in the way the two codes handle MUERR and stat diagonal matrices. But we checked, and that doesn't solve the issue

**Comment by RickKessler** [comment]
with a min/zmax cut, wfit does not carve out the cov_sys subset, which is likely causing the problem above.

**Comment by RickKessler** [comment]
fix sntools_output.c to select 1st varname on list  instead of last. E.g., for 'zHD zCMB', use zHD instead of  zCMB.  Note that the wfit.c line
    #define  VARLIST_DEFAULT_zHD     "zHD:D zCMB:D z:D Z:D"
was incorrectly selecting zCMB because both zHD and zCMB columns exist in the input Hubble diagram file. The wfit chi2 is still less than half of Ndof, so still need to do some digging.

**Comment by RickKessler** [comment]
the low chi2 seems to be confusion about which MUERR to use, so I will close this issue.
