### ISSUE TITLE
BBC INPUT_FITOPT000.FITRES: both gzipped and unzipped files created

### ISSUE THREAD

**Issue by CL-Raleigh** [RickKessler/SNANA#1107]
Hello,
somehting is not properly working in BBC.
For some reason, INPUT_FITOPT000.FITRES are correctly created but some are tarred, some are untarred and some are duplicates.

As a result, BBC crashed with the error.
```
  - FATAL ERROR ABORT called by open_TEXTgz
  - Found gzipped and unzipped file.
  - Cannot open both files.

``` 
You can reproduce the error looking at folder: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/MV-ROMAN_TRANS/6_BIASCOR/BBCRH_noLOWZsys/output_ITER1`

**Comment by RickKessler** [comment]
Recently, the gzipping of INPUT_FITOPT*.FITRES files was modified to gzip more quickly by doing parallel gzip with groups of 10 files. The problem above is that the number of files per group is 10 10 10 10 4 ... and the only the last gzip command did NOT have ampersand to force waiting before returning control to submit_batch. Gzipping 4 files is quicker than gzipping 10 files, and thus submit_batch moved on before all files were gzipped.

Two fixes were made. First, the gzip file groups are submitted in reverse order so that the group with missing ampersand (wait for gzip to finish) always has 10 files. Second, after control is returned to submit_batch, it counts the number of existing .gz files and doesn't return until the expected number of .gz files exists.
