### ISSUE TITLE
The initial values for alpha and beta (p1 & p2) result in conflicting best fits for alpha & beta.

### ISSUE THREAD

**Issue by RyanCamo** [RickKessler/SNANA#1118]
After our discussions last week Maria and I noticed that fitting for the mass step was not the culprit for our bias. Instead, it seems that the initial values for alpha and beta (p1 & p2) result in conflicting best fits for alpha & beta.
An example is shown in `$SNANA_DEBUG/ryanc/compare_p1p2_P21/`

**Comment by RickKessler** [comment]
please clarify "result in conflicting best fits for alpha & beta". What is the probem?

**Comment by RyanCamo** [comment]
Yeah no worries, so for the example linked above, when I use 
```
p1 = 0.155
p2 = 2.87
```
in my BBC input file, the best fit alpha and beta are:
```
alpha0:	  0.15691  0.00319
beta0:    2.94093  0.03226
```
However, when I use 
```
p1 = 0.140
p2 = 3.10
```
in the same BBC input file, best fit alpha and beta are:
```
alpha0:       0.14299  0.00318 
beta0:        3.17986  0.03158 
```
The initial values of p1 & p2 seem to significantly impact the results.

**Comment by RickKessler** [comment]
I think the problem is that for BS21 model, BBC's p2 input is not just the initial beta value, but there is an old BBC hack using p2 as the true fitted sim-beta for the biasCor sample ... because we don't know how to compute a true fitted-beta for BS21 model. Thus changing p2 (initial beta value) can change the BBC-fitted results.
