### ISSUE TITLE
Severe loss of SNe because of invalid BiasCor

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1128]
Severe loss of SNe because of invalid BiasCor.
In folder: `/project2/rkessler/PRODUCTS/SNANA_DEBUG/mvincenzi/validBiascor_bybin`

Three MUOPTs/zbins tested:
`- '/z1/ zmin=0.01 zmax=0.03 bins=1' --> MUOPT001`
`- '/z2/ zmin=0.025 zmax=0.04 bins=1' --> MUOPT002`
`- '/z3/ zmin=0.04 zmax=0.1 bins=1' --> MUOPT003`
For example in MUOPT001 we get:
`# WARNING(SEVERE): 28 of 59 events (47.5 %) have no biasCor for FOUNDATION
`

**Comment by RickKessler** [comment]
In the original BBC code (and paper), the z-range for the biasCor has to extend a little past zmax in order to interpolate the biasCor in the last z-bin. Somewhere in all the updates and refactors, this biasCor redshift-padding got lost (a bug). If zmax is past the detection of a survey, there is no impact from this bug. However, for running BBC with a limited z-range, the missing redshift padding results in a large loss of events due to invalid biasCor.
