### ISSUE TITLE
Unknown segmentation violation

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#1131]
There is an error that can be viewed at /scratch/midway2/rkessler/PIPPIN_OUTPUT/RC_DESPZ_MASTER/6_BIASCOR/P21NOM_IAonly/output/SCRIPTS_BBCFIT/OUTPUT_BBCFIT-0001_FITOPT000_MUOPT000.LOG that I've not seen before and am unable to track down.

I cannot reproduce the error with `FAIL_REPEAT_OUTPUT_BBCFIT-0001_FITOPT000_MUOPT000.CMD` this runs successfully

**Comment by RickKessler** [comment]
This job above uses NSPLITRAN, and it likely conflicts with a recent refactor to speed up the BBC preparation.

**Comment by rebeccachen0** [comment]
For what it's worth, I didn't run into the same issue here: /scratch/midway2/rkessler/PIPPIN_OUTPUT/RC_DESPZ_MASTER/6_BIASCOR/P21NOM which I also ran recently using NSPLITRAN

**Comment by RickKessler** [comment]
It is indeed a subtle bug with recent refactor, but it has nothing to do with NSPLITRAN. The gzipping is divide into 10 cores, but in above job only 1 core is needed and the wait-for-gzip logic didn't wait. Fix is to check wait upon reaching 10 gzip jobs, or if there are fewer than 10 gzip jobs.

I also added more robust logic to not only require a certain number of INPUT*FITRES.gz files, but also require zero INPUT*FITRES files so that BBC doesn't start while gzip is still going.
