### ISSUE TITLE
SIM_HOSTLIB_GALID =/= GALID in hostlib

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#1132]
Looking at the FITRES output of LCFIT, there are SIM_HOSTLIB_GALID that are not present in my original HOSTLIB.
e.g. 24010706944

This is the FITRES: /scratch/midway2/rkessler/PIPPIN_OUTPUT/RC_DESPZ_MASTER/2_LCFIT/DFIT_DES_P21/output/PIP_RC_DESPZ_MASTER_DES_P21/FITOPT000.FITRES

and the HOSTLIB used for the simulation is at $DES_USERS/rebeccachen/PZQ/hostlibs/buzzard_wide_sompz+masses_sfr_mask.HOSTLIB

**Comment by RickKessler** [comment]
On March 28 2023, I had fixed several casting errors for GALID (int instead of long long int) because allocating only 4 bytes can corrupt values larger than a few billion. Your job has SUBMIT.INFO file from Mar 27, FITRES files with Apr 3 date stamps, and SPLIT_JOBS_LCFIT from about a week later. In short, I am not sure when your sim and LCFIT actually ran. Please re-run both sim and LCFIT to check if the March 28 code update fixes the casting problem.

**Comment by rebeccachen0** [comment]
After rerunning sim and LCFIT, the same problem persists.

$PIPPIN_OUTPUT/RC_DESPZ_MASTER/2_LCFIT/DFIT_DES_P21/output/PIP_RC_DESPZ_MASTER_DES_P21
e.g. 24010706944

**Comment by RickKessler** [comment]
so the sim and LCFIT output tables are indeed ok writing GALID ... the problem is in the merging where the FITRES files are catenated.

**Comment by RickKessler** [comment]
FITRES file VARNAMES like CID and GALID are automatically read as string (instead of int) to avoid corruption for very large values that don't fit into 4-byte allocations. However, HOSTGAL_OBJID was not checked, and partial matches (e.g., SIM_HOSTLIB_GALID) were not checked either. Fixed function ICAST_for_textVar(VARNAME)  so that partial VARNAME matches to OBJID and GALID are cast as string.
