### ISSUE TITLE
LCFIT+z for p(z) quantiles previously working but now broken

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#1134]
Using OPT_PHOTOZ=4 (LCFIT+z with a full p(z) for the host prior) was previously working but is now triggering the following error:
`gsl: interp.c:83: ERROR: x values must be strictly increasing
Default GSL error handler invoked.`
for every SN.

Checking the quantiles for the host galaxy confirms they are in fact strictly increasing -- I'm wondering if this has to do with some casting error.

Error can be seen in $PIPPIN_OUTPUT/RC_DESPZ_MASTER/2_LCFIT/DFIT_DES_P21/output/SPLIT_JOBS_LCFIT/PIP_RC_DESPZ_MASTER_DES_P21_FITOPT001_SPLIT005.LOG CID=4211626
and confirming the increasing quantiles (CID=4211626) can be seen at $PIPPIN_OUTPUT/RC_DESPZ_MASTER/2_LCFIT/DFIT_DES_P21/output/PIP_RC_DESPZ_MASTER_DES_P21/FITOPT000.FITRES
for this CID

**Comment by RickKessler** [comment]
all of the zphot_q values are -9; e.g., 
cd $PIPPIN_OUTPUT/RC_DESPZ_MASTER/2_LCFIT/DFIT_DES_P21/output/RICK_DEBUG
quick_commands.py -v PIP_RC_DESPZ_MASTER_DES_P21 --cidlist_text 9574900
grep ZPHOT_Q PIP_RC_DESPZ_MASTER_DES_P21_TEXT/DES_9574900.DAT 

Tomorrow I will at least try to set an abort trap with a sensible error message to avoid core dump.

**Comment by rebeccachen0** [comment]
This is odd, because the FITOPT000 `$PIPPIN_OUTPUT/RC_DESPZ_MASTER/2_LCFIT/DFIT_DES_P21/output/PIP_RC_DESPZ_MASTER_DES_P21/FITOPT000.FITRES` (OPT_PHOTOZ=0) corresponding to the same simulation does show values for the zphot_q values, so somehow the zphot_q values are not being propagated correctly in the OPT_PHOTOZ=4 case?

**Comment by RickKessler** [comment]
I think the problem is that your HOSTLIB varnames include
   ZPHOT_Q0 ZPHOT_Q10 ZPHOT_Q20 ZPHOT_Q30 ZPHOT_Q40 ...

but the integer part has to be %3.3d format,
  ZPHOT_Q000 ZPHOT_Q010 ZPHOT_Q020 ZPHOT_Q030 ZPHOT_Q040 ZPHOT_Q05
0 ZPHOT_Q060 ZPHOT_Q070 ZPHOT_Q080 ZPHOT_Q090 ZPHOT_Q100

The sim doesn't care, but read-back with snlc_fit.exe seems to require %3.3d format.
This is rather fragile and should be cleaned up when we have a more stable code. I will add a check to abort if there are fewer than 3 characters after the _Q

**Comment by RickKessler** [comment]
crash was from running "make" instead of "make clean; make"
