### ISSUE TITLE
Best way to output "transition time" parameter in CLAGN model

### ISSUE THREAD

**Issue by qifengcheng** [RickKessler/SNANA#1139]
We are working on a generalization of AGN model and going to introduce the changing look behavior, and we intend to output the transition time parameter in hope that it can have some practical usage in the future. 

Our code generates "transition time" parameter, which is sampled uniformly from [minimum trest; maximum trest] interval. Right now we output this parameter as is, in a rest frame, but users probably would like to have it in MJD, not in rest-frame time. However, we don't have MJD corresponding to zero rest frame time (is it the same as PEAKMJD?) inside Python SED models. How do you think, what would be the best option for this case? We see three variants: 1) output trest transition, 2) output "trest transion" * (1 + z), 3) update C code to pass MJD inside Python and output MJD transition

**Comment by RickKessler** [comment]
please provide command to run AGN sim for a few events.

**Comment by qifengcheng** [comment]
> please provide command to run AGN sim for a few events.

Sure! You can run `./run.sh` in $SNANA_LSST_USERS/qifeng/ to produce 100 sim

**Comment by RickKessler** [comment]
t_transition isn't fixed yet, but here are a few minor refactors to move in the right direction. 
First, MJDOFF = GENRANGE_MJD[0] is passed as argument to genmag_PySEDMODEL. MJDOFF isn't used yet, so later need to pass MJDOFF to python code so that it can do t_transition+=MJDOFF.

To avoid confusion about GENRANGE_[PEAKMJD,TREST], AGN are treated the same way as recurring LCLIB events: sim-input GENRANGE_MJD must be provided , and sim-inputs GENRANGE_[PEAKMJD,TREST] are ignored.

**Comment by hombit** [comment]
Thank you! Could you please clarify few points?

Who should provide GENRAGE, the model or a user in an INPUT file? Why do we need time-range restrictions while the given model is analytical one and could generate as long light curve as requested?

Does MJDOFF correspond to zero trest the Python model consumes in prepEvent and fetchSED? Does it mean that if the model's internal t_transition in the rest frame, we really should do mjd_transition = MJDOFF + t_transition * (1 + HOST_REDSHIFT)?

**Comment by RickKessler** [comment]
Going to close this issue until the request is needed.
