### ISSUE TITLE
HEADER_OVERRIDE_FILE does not work for ZPHOT_QXXX

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#1140]
I am using a HEADER_OVERRIDE_FILE to provide zphot quantiles, but the "zPDF quantiles requested for photo-z fit but there are no zPDF quantiles in the data." error is being triggered. The override works fine for normal HOSTGAL_ZPHOT overrides, just not quantiles-- not sure if HOSTGAL_ZPHOT_QXXX variables are checked for in a header override.

Directory is: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/RC_DESPZ_MASTER/2_LCFIT/DATAFIT_DATADES/output`

**Comment by RickKessler** [comment]
try adding NZPHOT_Q column in hEADER_OVERRIDE file

**Comment by rebeccachen0** [comment]
Added NZPHOT_Q column, but am getting the same error (same directory)

**Comment by RickKessler** [comment]
This fix was tricky because data files don't contain quantiles and thus the default override procedure doesn't even check the quantiles. Even if the data includes quantiles, the number of override quantiles could be different than the original. I therefore added a new rd_override_zphot_q() function (in sntools_data.c) that always forces an override regardless of whether quantiles exist or not.

To select events on the override list,
&SNLCINP
HEADER_OVERRIDE_FILE =        '$DES_USERS/rebeccachen/PZQ/hostlibs/data_sompz_override.HOSTLIB'
SNCID_LIST_FILE   = 
   '$DES_USERS/rebeccachen/PZQ/hostlibs/data_sompz_override.HOSTLIB'

where the argument is the same for HEADER_OVERRIDE_FILE and SNCID_LIST_FILE. There is no need to construct a separate CID list file. To more robustly select events from an override file, I added this new feature,
      SNCID_LIST_FILE  = 'HEADER_OVERRIDE_FILE'
will internally replaces HEADER_OVERRIDE_FILE with its argument. Thus the HEADER_OVERRIDE_FILE argument can be altered and the SNCID_LIST_FILE is automatically synced.

**Comment by RickKessler** [comment]
Beware that the above fix has only been tested to run without aborting. More testing is needed on the fit results.
