### ISSUE TITLE
strange output from create_covariance.py ?

### ISSUE THREAD

**Issue by RickKessler** [RickKessler/SNANA#1141]
cd $PIPPIN_OUTPUT/D5YR_SMP_V1/7_CREATE_COV/COV_OMW_P21NOM/output/SCRIPTS_COVMAT
more COVMAT_COV_OMW_P21NOM_P21NOM_SIGINT_COLOR_OUTPUT_BBCFIT.LOG 

and note 1.4 million stdout lines of the form,
  2013E_56 1 missing from output/cosmomc/data_wCID.txt

I traced this comment in the code and 'output/cosmomc/data_wCID.txt' is a hard-wired file name and does not correspond to anything used by create_covariance.

What does this error message mean, and does it suggest a problem?

**Comment by djbrout** [comment]
this has to do with building in the peculiar velocity systematics/covariance from pre-computed matrices being specified here:
`/scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_SMP_V1/D5yr_SMP_v1.yml`
this is the code that has the precomputed matrix. 
```      EXTRA_COVS:
	- "VPEC_2MRS_DIAG .7 $PS1MD_USERS/dscolnic/PANTHEON+/2mrs_stat_v2.cov"
```
this is fine... its good to keep the warning message. the reason Maria sees so many warnings is because she has a smaller subset of lowz SNe than what is in 2mrs_stat_v2.cov
