### ISSUE TITLE
YSE SALT3 simulation is not using SIMLIB redshift even with USE_SIMLIB_REDSHIFT: 1 

### ISSUE THREAD

**Issue by gnarayan** [RickKessler/SNANA#1163]
Input files, searcheff, simlib are all on perlmutter at $SNANA_LSST_USERS/gnarayan/YSE/REFAC_SIMGEN_YSE_ZTF_NOBATCH.INPUT

We compiled a version of snlc_sim.exe with a few extra print statements, and then CUTWIN check failed.
We commented out all the CUTWIN cuts in the input file and then uncommented one by one to determine that REDSHIFT cut is the issue. 
We found that output light curves have -9 for the redshift but the SIMLIB has reasonable redshifts - can verify with:
grep REDSHIFT yselc_grizXY_dr1.simlib

So unclear why snlc_sim.exe is ignoring the redshift.

**Comment by RickKessler** [comment]
The problem is in the sim-input file and is rather subtle. Start with this grep,

grep SEARCHEFF_ REFAC_SIMGEN_YSE_ZTF_NOBATCH.INPUT 
APPLY_SEARCHEFF_OPT:  1
SEARCHEFF_PIPELINE_EFF_FILE: $SNANA_LSST_USERS/gnarayan/YSE/SEARCHEFF_PIPELINE_YSE_DR1_SNR4_grizXY.DAT
SEARCHEFF_PIPELINE_LOGIC_FILE: $SNANA_LSST_USERS/gnarayan/YSE/SEARCHEFF_PIPELINE_LOGIC_ZTF.DAT
SEARCHEFF_SPEC_FILE:  ZERO
SEARCHEFF_zHOST_FILE:  ZERO

The last two lines state that Eff(spec-confirmation) = 0 and that Eff(zHOST) = 0;  thus there is no source of measuring a redshift, resulting in redshift = -9. The easy fix is to remove the SEARCHEFF_SPEC_FILE line, or override the ZERO argument with
   snlc_sim.exe  REFAC_SIMGEN_YSE_ZTF_NOBATCH.INPUT \
          SEARCHEFF_SPEC_FILE  NONE

If there is no SEARCHEFF_SPEC_FILE key in sim-input, the default EFF(spec-confirmation) = 1.0 and all events will have accurate zSpec.

**Comment by gnarayan** [comment]
Thanks! I'd have been scratching my head about this one for a bit...
