### ISSUE TITLE
GSL error

### ISSUE THREAD

**Issue by jasonlee17** [RickKessler/SNANA#1198]
Hi Rick, 

As I mentioned earlier - when I run `snlc_sim.exe SNIa_astro_z0.0_to_1.2_v0904.input NGEN_LC 100` , 

I get the error below while the light-curve is being generated: 

gsl: view_source.c:29: ERROR: matrix dimension n1 must be positive integer
Default GSL error handler invoked.
Aborted (core dumped)

Here is the path to my input files: /project2/rkessler/SURVEYS/DES/USERS/jasonlee/GSL_error

This did work last week, so I'm wondering if there's been any updates that's causing a conflict. 

Thanks!
Jason

**Comment by RickKessler** [comment]
in a recent update to avoid slow Cholesky deconp, 
   https://github.com/RickKessler/SNANA/issues/1195
the current crash is because NOBS=0 (after SNR>2 cut) passes a zero-size matrix to Cholesky decomposition. The fix is to skip the decomposition in this case.

As an aside, see fixed SIMGEN_DUMP argument.
