### ISSUE TITLE
ELAsTiCC round 2, unexpected values for some host galaxy fields in stream

### ISSUE THREAD

**Issue by ale-munozarancibia** [RickKessler/SNANA#1210]
Hi, I was inspecting the objects we (ALeRCE) have ingested in ELAsTiCC2 and found some weird things. I wanted to ask if they match what was sent in alerts, and if they do, confirm if they were intended or not. Things found affect only some objects (not full columns as in e.g. `hostgal_zphot_q070`):
- Objects with undefined values for `hostgal_ellipticity` have "-9999", but there are also objects with "-999" in that column. Same for `hostgal_sqradius`, `hostgal2_ellipticity` and `hostgal2_sqradius`
- Objects with undefined values for `hostgal_zphot_q000` have "-9", but there are also objects with a distribution around that value (see plot). Same for `hostgal2_zphot_q000`
- There are objects with negative values for `hostgal_magerr_<filter>` (see example plot for `hostgal_magerr_u`). Same for `hostgal2_magerr_<filter>`

![distrib_hostgal_zphot_q000](https://github.com/RickKessler/SNANA/assets/42121847/c48eab98-b5db-4810-875e-766bf5faebd7)
![distrib_hostgal_magerr_u](https://github.com/RickKessler/SNANA/assets/42121847/dd0636f8-dd60-480e-a8bc-15c8e921194b)

**Comment by RickKessler** [comment]
for the first issue regarding hostgal_ellipticity and hostgal_sqradius, -9999 means that the variables were not defined in the HOSTLIB (e.g., Galactic transients), but I am not sure where -999 is from. Values of -9 mean the variable is defined, but has no host match. These different null values are used to help analysis codes know what to read or ignore. 

Can you provide a few SNIDs that have -9999 and -999 values?

**Comment by RickKessler** [comment]
For third issue (crazy u-band error), this is indeed from the HOSTLIB, so I passed a few examples to Alex Gagliano. Not sure if it's a translation error or an issue in PZRAIL that we didn't notice.

**Comment by ale-munozarancibia** [comment]
Thanks @RickKessler! Here I list some SNIDs:

hostgal_ellipticity=hostgal_sqradius=-9999: 30193464, 55444095, 111565674
hostgal_ellipticity=hostgal_sqradius=-999: 34432060, 107067312, 152847047

**Comment by RickKessler** [comment]
sqradius = -9999 means that this variable never defined
SNID         model    comment
30193464      EB       expect sqradius = -9999 since there is never a host
111565674     d-Sct    expect sqradius = -9999 since there is never a host
55444095      AGN      no DLR match, but expect -9 since AGN has host <== BUG?

sqradius = -999 :
34432060, 107067312, 152847047  are all AGN; the sqradius=-999 value
is from UNMATCHED_COSMODC2_GHOST.HOSTLIB, and thus likely an artifact
passed from DC2. LOGMASS values are reasonable and r mag is 25-26 range.
A naive hypothesis is that these galaxies failed the fit profile fit,
but a0 and b0 Sersic params have reasonable values, which contradicts
the failed fit hypothesis.

GALID        ELLIPTICITY  SQRADIUS  LOGMASS     r_obs  a0_Sersic  b0_Sersic
10388686378       -999.0    -999.0   9.6731  26.36355     0.5402     0.2467
6067270670        -999.0    -999.0   8.1327  25.26386     0.1282     0.1209
7829141059        -999.0    -999.0  10.0498  25.07678     0.2248     0.2240

**Comment by RickKessler** [comment]
The crazy u-band error seem to be from very faint (mag~30) events where there is no significant flux. Will fix SNANA to set magerr= 9.0 for negative magerr or magerr<9.

**Comment by ale-munozarancibia** [comment]
Hi @RickKessler, I just noticed I didn't include SNIDs about the hostgal_zphot_q000 issue, here they are:

11934165, hostgal_zphot_q000=-12.560043334960938
41902133, hostgal_zphot_q000=-12.394664764404297
72154970, hostgal_zphot_q000=-11.587726593017578

**Comment by RickKessler** [comment]
gonna close this issue for now, but re-open of new ELASTICC sim has similar problems
