### ISSUE TITLE
 +HOSTAPPEND hangs 

### ISSUE THREAD

**Issue by ykangastro** [RickKessler/SNANA#1211]
An issue with +HOSTAPPEND. The code was stuck. 
Bash script: /global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/EAZY/host_append.sh

**Comment by RickKessler** [comment]
The +HOSTAPPEND feature did not technically hang; instead, the brute-force GALID matching is very slow for > 1 million rows. It would have eventually finished after many hours. I replaced the brute-force GALID matching with hash-matching utility, and the matching now takes few seconds instead of hours. Revert back to brute-force with DEBUG_FLAG  -1009.

Also added check on the appended VARNAMES to remove duplicates in the original HOSTLIB. E.g., it removes ZTRUE column that already exist in HOSTLIB.
