### ISSUE TITLE
Match error between SIM_REDSHIFT_HOST and the redshift in HOSTLIB input file

### ISSUE THREAD

**Issue by bastiencarreres** [RickKessler/SNANA#1245]
Hi,

When simulating using a HOSTLIB with the redshift match option I noticed a discrepancy between the stored redshifts `SIM_REDSHIFT_HOST` and the input redshifts in the HOSTLIB.

I've setup an input file at `/project2/rkessler/SURVEYS/PS1MD/USERS/bcarreres/DEBUG_Z/SIMGEN_LOWZ_DEBUGZ.INPUT`
that result in a simulation at `/project2/rkessler/PRODUCTS/SNDATA_ROOT/SIM/DEBUG_Z/`. The DUMP file contains  the `GALID` that allow to retrieve the HOST from the HOSTLIB: `/project2/rkessler/SURVEYS/PS1MD/USERS/bcarreres/SIMLIB/PanthP_HOSTLIB.HOSTLIB`

The config for host is:
```
HOSTLIB_FILE: /project2/rkessler/SURVEYS/PS1MD/USERS/bcarreres/SIMLIB/PanthP_HOSTLIB.HOSTLIB
HOSTLIB_MSKOPT: 536 # Use Host coord (+8), adjust SN redshift (+16), and peculiar velocity (+512) 
HOSTLIB_DZTOL: 0.0001 0 0 
HOSTLIB_STOREPAR: VPEC,ZTRUE_CMB,GROUPID,UCHUUID

VEL_CMBAPEX: 0 # Cancel vel CMB
```
The DZTOL is set to 1e-4 but we can observe a discrepancy up to 1e-3.

**Comment by RickKessler** [comment]
with your option VEL_CMBAPEX=0, there were still a few places where the CMB<->HEL translator was applied and thus inconsistent with other parts of the code. I add previously missed checks in transform_ZTRUE_HOSTLIB()  and SORT_SNHOST_byDDLR(). 

Beware that since VPEC is in your HOSTLIB, but not VPECERR, VPEC is applied without fluctuation. The reported REDSHIFT_HELIO and REDSHIFT_FINAL include uncorrected VPEC, and thus differs from ZTRUE_CMB.

**Comment by RickKessler** [comment]
To verify the original ZTRUE_CMB in the HOSTLIB, run the script
 ././MAKE_SNANA_TABLE.sh
and check zHD column printed to stdout. SNANA analysis jobs apply vPec correction to zCMB and report zHD (redshift to use with Hubble diagram). In this case with VPECERR=0, zHD is the true CMB redshift.

**Comment by bastiencarreres** [comment]
Resolved.
