### ISSUE TITLE
sim_template_index issue with BBH simulations

### ISSUE THREAD

**Issue by simran2296** [RickKessler/SNANA#1263]
We are facing an issue with our BBH simulations with SNANA where we have about 2000 templates. As we run the simulation, the sim_template_index the output has are 0,1 and 2 only. This issue doesn't occur with simulations of other objects like KNe and SNe (for instance, KNe simulations are uniformly drawn from 329 Kasen models and output seems to draw indices uniformly within this range from 1 to 329. ) 
I am sharing with you the templates and SIMGEN input we use for BBH sims.
BBH templates: /data/des40.a/data/nsherman/DESFollowup_Testing/FromTristan/bbh_models/SIMSED.BBH/SIMSED.BBH
BBH SIMGEN input file: /data/des80.a/data/simrankj/DES_Followups/templates/SIMGEN_DES_BBH.input

**Comment by RickKessler** [comment]
FATAL ERROR ABORT called by SIMLIB_readGlobalHeader_TEXT
   Could not find 'SIMLIB_FILE' input file:
   SIMLIB.txt  (see preAbort info above)

and also suggest making binary file so that initialization is much faster.

**Comment by simran2296** [comment]
The simlib file is here
/data/des80.a/data/simrankj/DES_Followups/events/GW190814_bbh_test/sim_gen/SIMLIB.txt

**Comment by RickKessler** [comment]
Problem is that SED.INFO file has multiple PARNAMEs with INDEX (or index) in the name:
   BBH_INDEX  rise_index  fall_index
and the sim code was using the last one (fall_index) instead of the correct BBH_INDEX. 
To avoid ambiguity, sim code has been updated to abort on multiple PARNAMEs containing INDEX or index string. The latter two variables must be renamed without 'index'.

Other miscellaneous problems:
* remove tabs from SED.INFO file (causes problems with parsing)
* GENRANGE_MJD and GENRANGE_PEAKMJD do not overlap MJD range of SIMLIB, and this result in zero events processed.

**Comment by RickKessler** [comment]
Minor issue for future SIMSED models.
Here is a typical entry in one of your SED text files:
34.95000000000003 29970.0 6.889466338307483e+32

If this were formatted more compactly,
34.95 29970.0 6.889e+32

it would consume half the disk space and probably initialize x2 faster.
