### ISSUE TITLE
Computed zCMB (from zHEL) outside tolerance

### ISSUE THREAD

**Issue by am610** [RickKessler/SNANA#1265]
Location : `$PIPPIN_OUTPUT/LSST_BIASCOR+TRAIN_PHOTOZ_V3/2_LCFIT/LSST_LSST_BIASCOR_Ia/output/`
Got this error : 

```
FAILURE-0001:
  JOB_LOG_FILE:       PIP_LSST_BIASCOR+TRAIN_PHOTOZ_V3_LSST_BIASCOR_Ia_FITOPT000_SPLIT020.LOG 
  FAIL_REPEAT_SCRIPT: FAIL_REPEAT_PIP_LSST_BIASCOR+TRAIN_PHOTOZ_V3_LSST_BIASCOR_Ia_FITOPT000_SPLIT020.CMD 
  FAIL_MODE:          ABORT 
  ABORT_MESSAGES: 
  - FATAL ERROR ABORT called by SET_ZHELIO 
  - Computed zCMB (from zHEL) outside tolerance w.r.t. 
  - REDSHIFT_CMB in data file for CID=16166829 
```
setting  `zTOL_HELIO2CMB  = 0.2` will take this error away.

**Comment by RickKessler** [comment]
This is a very odd case involving two subtle bugs. First, there is an old option to use host photo-z for every event with
   GENSIGMA_REDSHIFT:  1.0
The first bug is that this option sets both REDSHIFT_HELIO and REDSHIFT_CMB equal to ZPHOT_HOST, which can fail the zTOL (zHEL<->zCMB) test in snlc_fit.exe.

However, this bug is not what caused the above abort because the above sim-input has "GENSIGMA_REDSHIFT: 0" and uses zHOST efficiency map to determine which subset of events has zPHOT (instead of zSPEC). The above event selected a very rare galaxy that has zPHOTERR > 1.0. This triggered the 2nd bug in which the actual zERR > 1 was used to set REDSFHIT_HELIO = REDSHIFT_CMB = zPHOT_HOST, instead of checking the user input GENSIGMA_REDSHIFT.

Both bugs have been fixed.

To avoid the zTOL abort when running snana.exe/snlc_fit.exe on old sims with the above-mentioned bugs, the zTOL test is skipped when SNLC_ZHELIO_ERROR >. 1.0.
