### ISSUE TITLE
requests for resimulate_with_spectra.py

### ISSUE THREAD

**Issue by RickKessler** [RickKessler/SNANA#1268]
* remove -f arg and make input yaml file a positional argument since it is required
* replace default store_inputs/ with store_resimulate_inputs/  for clarity 
* resimulate_with_spectra.py <input> --extra_sim_args “bla arg1 bla2 arg2” which adds these extra command line arguments to snlc_sim.exe command.
* replace print() commands with logging.info() ... or add sys.stdout.flush() after each print. This is needed so that stdout is in correct order when redirecting to a log file.

**Comment by AmandaWasserman** [comment]
- [x] remove -f arg and make input yaml file a positional argument since it is required
- [x] replace default store_inputs/ with store_resimulate_inputs/ for clarity
- [x] resimulate_with_spectra.py --extra_sim_args “bla arg1 bla2 arg2” which adds these extra command line arguments to snlc_sim.exe command.
- [x] replace print() commands with logging.info() ... or add sys.stdout.flush() after each print. This is needed so that stdout is in correct order when redirecting to a log file.
