### ISSUE TITLE
Log file not being written on lcfit failure

### ISSUE THREAD

**Issue by darcykenworthy** [RickKessler/SNANA#1277]
When FILTLIST_FIT is incorrect, Pippin isn't terminating because an ALL.DONE file isn't being written. 

Pippin input file that reproduces issue:

/project2/rkessler/SURVEYS/DES/USERS/dkenworthy/pippinlearning/darcytesting.yml

See issue submitted here
[dessn/Pippin#155](https://github.com/dessn/Pippin/issues/155)

**Comment by RickKessler** [comment]
Before investigating abort, need to figure out why submit_batch jobs continued forever. By default, a failure does not trigger "kill_jobs" unless user explicitly specifies the           --kill_on_fail option. The above jobs uses the event-sync option (opt_sncid_list) that requires FITOPT000.FITRES to exist before processing FITOPT001, etc ... So when the first (FITOPT000) fit job fails, the CPU*.CMD script hangs on infinite wait. 

The fix is to internally set args.kill_on_fail = True when event-sync is selected, and to also add a supplement kill_on_fail check in the submit_batch code, in addition to the check in the CPU*.CMD scripts.

**Comment by RickKessler** [comment]
The abort seems to be due to a mix-up in defining filters for LOWZ vs. FOUNDATION.
