### ISSUE TITLE
Mysterious segfaults when running non-Ia templates 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#1279]
Morning! Getting a lot of segfaults here --
/scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-DES-ZTF-TEST/1_SIM/TRAINDES_V19/LOGS/FAIL_SUMMARY.LOG

an example of that being in this log file 
TMP_bap3_PIP_BP-DES-ZTF-TEST_TRAINDES_V19_SNIaMODEL0-0001_24659.LOG

In addition, there's some incredibly frustrating SIMSED-BINARIES mismatches going on that seem to be ignoring my best attempts to fix them, those are under the boatload of segfaults.

**Comment by RickKessler** [comment]
Above sim uses original SIMSED.SNIax under $PLASTICC_ROOT/model_libs. However, Fig 4 of https://arxiv.org/pdf/2012.07180.pdf shows an improved SNIax model that we have been using since, and it is located under $PLASTICC_ROOT/model_libs_updates/SIMSED.SNIax . Thus the original SNIax binary is likely stale, but the updated one is Ok. Your test job reads the newer SNIax model fine, but aborts on filter-inconstancy:

 FATAL ERROR ABORT called by gen_cutwin
   Invalid filter 'i' in
   CUTWIN_SNRMAX: 3.0  griz   etc ...

**Comment by bap37** [comment]
Thank you! I don't know how to update this, then. I have tried to update the binaries using the file here -- 

/project2/rkessler/SURVEYS/LSST/ROOT/PLASTICC/model_libs/SIMSED_BINARIES/config_DESgr/make_simsed_binaries_DES.yaml

which points to the new libraries, but it results in a bunch of the above failings and I don't know where the mismatch is

**Comment by bap37** [comment]
oops ! Forgot to leave the directory where all the errors are! 

/scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-DES-ZTF-TEST/1_SIM/TRAINDES_V19/LOGS/FAIL_SUMMARY.LOG

**Comment by RickKessler** [comment]
works fine for me if this line is removed:
   CUTWIN_SNRMAX:   3 griz 2 -20. 60.

or replaced with griz -> gr
