### ISSUE TITLE
SIMSED SED Physical Prior Error

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#1280]
I'm attempting to run a model with some priors to weight specific SED files by their physical parameters, like so (from `SIMGEN_INCLUDE_SNPRECURSOR.INPUT`): 
```
# bifurcated gaussian -- assume no difference in sigma for now.
SIMSED_PARAM:  Rstar
GENPEAK_Rstar: 460
GENRANGE_Rstar: 100.   1000.
GENSIGMA_Rstar: 300.  300.
```
This causes a crash. 

_Location on Perlmutter:_ `/global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/agaglian/Precursor_32kGrid`

_Command:_
`snlc_sim.exe SIMGEN_TEMPLATE_LSST.INPUT`

_Error:_
```
 ****************************************************************** 
    Begin Generating Lightcurves.   
  Found Max dN/dz * wgt = 6.969921e+04 at z =    0.300 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by interp_flux_SIMSED
   Dimension 1 does not have enough data points in lower sheet (1).
   PRERSG_INDEX = 26748.000000
```

**Comment by RickKessler** [comment]
Please make sure that all sim-input files (in addition to main sim-input file) have group-read permission:

FATAL ERROR ABORT called by init_SEARCHEFF_LOGIC
   Could not find 'SEARCHEFF_PIPELINE_LOGIC_FILE' input file:
   /global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/agaglian/precursorSandbox/SEARCHEFF_PIPELINE_LOGIC_LSST.DAT  (see preAbort info above)

cat /global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/agaglian/precursorSandbox/SEARCHEFF_PIPELINE_LOGIC_LSST.DAT
-bash: /global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/agaglian/precursorSandbox/SEARCHEFF_PIPELINE_LOGIC_LSST.DAT: Permission denied

**Comment by alexandergagliano** [comment]
_sigh_ This is now fixed.

**Comment by RickKessler** [comment]
in SIMGEN_INCLUDE_SNPRECURSOR.INPUT the Gauss profile was added but "SIMSED_GRIDONLY:  PRERSG_INDEX" was not removed, resulting in conflict. Later I will fix sim to abort on these conflicting requests.

I commented out the SIMSED_GRIDONLY key, and sim aborts with
 FATAL ERROR ABORT called by interp_flux_SIMSED
   Corners[0] already filled; two data points have the same coordinates.

The problem is that the SED grid is really 5D, so giving only 1D to interpolate is ambiguous because all of the values are repeated many times, and it can't figure out which SED you want. Try defining Gauss profile in all 5 dimensions; set large sigma to get flat distribution.
