### ISSUE TITLE
Number of candidates with LCFIT+z convergence different between v11_05l and v11_05i

### ISSUE THREAD

**Issue by jasonlee17** [RickKessler/SNANA#1320]
Hi Rick, 

As mentioned a few days ago, I found that running LCFIT+z in the Perlmutter DESC-TD environment with the current tag (`v11_05l`) results in a smaller number of LCFIT+z converged candidates compared to my previous set of runs in January with `v11_05i` even if the input file is the same. 

In `/global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/jasonlee/FITRES_240329/` I have two runs (that I did yesterday) with each of the versions for the case of SN Photo-z only (so no priors). 

If you look in `LCFIT+z_OUTPUT_REALISTIC_SN_PHOTOZ_ONLY/FITOPT000.FITRES` for the two versions, you will see that the number of candidates are different; the `v11_05i` contains all of the `v11_05l` ones + several hundred more. The .NML file I used for these runs are also in these folders. 

This difference was most striking when I supplied a host photo-z prior (more than 10% difference in the number of LCFIT+z converged candidates). 

Let me know what changed, and if it's okay to continue using the `v11_05i` runs. 

Also, because the MERGE variables changed (NEVT_SNANACUT => NEVT_LC_CUTS), I have to merge the completed 30 split jobs manually, and I am not able to append the PRIORCHI2 when I do this... it would be great if you could let me know how to get around this. 

Best, 
Jason

**Comment by RickKessler** [comment]
Here is a recent code block (snana.car) that forced rejecting an event if there is no quantile information, but this logic cannot not check if quantiles are requested in snlc_fit; thus it spuriously rejected events for SN-only photo-z fits. Fix is to remove this code block, and hopefully the newer MASK_REDSHIFT_SOURCE  logic is adequate.

c xxxxxxxxxx Apr 1 2024 mark delete xxxxxxxxx
c  BAD LOGIC BECAUSE IT TAKES EFFECT EVEN IF QUSNTILES ARE NOT REQUESTED
c
c	IF (igal == 1) THEN
c	   LTMP = (SNHOST_ZPHOT_Q(igal,1) < -0.001) .AND. 
c     &        (SNLC_REDSHIFT > QUANTILE_ZERRMIN)	   
c	   IF (LTMP) SNLC_REDSHIFT = -9.0 ! Forced event to be rejected
c	ENDIF
c xxxxxxxxx end mark xxxxxxxxxx
