### ISSUE TITLE
Running snlc_sim.exe on resim input files

### ISSUE THREAD

**Issue by AmandaWasserman** [RickKessler/SNANA#1366]
Running: `snlc_sim.exe ELASTICC2_FINAL_RRL_cid47454014_mjd60851.02_new.input`  in the folder `/global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/amandaw8/store_resim_inputs` leads to  `*** Break *** segmentation violation`

~~realizing this may be an issue with RRL which we probably won't encounter once we only consider SN-like objects? In the mean time Rob is giving me all sources

And running: `snlc_sim.exe ELASTICC2_FINAL_SNIa-SALT3_cid54097308_mjd60808.133_new.input` in the same folder leads to 
```
FATAL ERROR ABORT called by read_specTable_HOSTLIB
   Could not find 'HOSTLIB_SPECBASIS_FILE' input file:
   SIMGEN_EAZY_TEMPLATES.INPUT 
```

~~ I realized the issue with this is needing to have SIMGEN_EAZY_TEMPLATES.INPUT in the store_resim_input folder. How do we ensure that this is set up in the resim folder? Or should we store it elsewhere in NERSC?

Jupyter notebook where I created the resim input files is /global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/amandaw8/run_full_sim.ipynb

**Comment by RickKessler** [comment]
the sim cannot generate spectra for LCLIB (Galactic) models because there is no SED representation. The code flags a warning, then continues and crashes since I didn't disable some flags. It is now fixed to give warning

 WARNING called by init_genSpec
   Spectrograph option not available for
   INDEX_GENMODEL=12 (LCLIB)

and then continue generating without spectra.
