### ISSUE TITLE
BBC_ACCEPT_SUMMARY.LIST is not being created

### ISSUE THREAD

**Issue by benjaminrose** [RickKessler/SNANA#1373]
I am trying to do a stats only 0D BBC fitting. However the job crashes when it can't find the CID Table file, BBC_ACCEPT_SUMMARY.LIST.

Running `$SNANA_ROMAN_USERS/brose3/roman/BR-KW-lensing.yml` and the failed output can be seen in `$PIPPIN_OUTPUT/BR-KW-LENSING/6_BIASCOR/BBC_LENSED`.

**Comment by RickKessler** [comment]
in the BBC input, remove "-hsteps 121"  from this line
WFITMUDIF_OPT: -ompri 0.311 -dompri 0.01  -wmin -1.5 -wmax -0.5 -wsteps 201 -hsteps 121

the hmin/hmax/hsteps arguments had been in wFit for a very long time even though they were not used due to analytic marginalization. A few months ago I removed these obsolete arguments, and thus the code aborts when using them.

**Comment by benjaminrose** [comment]
That fixed it. Thanks.
