### ISSUE TITLE
Simulation runs for 24 hours and cuts off when changing MJD ranges

### ISSUE THREAD

**Issue by jmpaulin** [RickKessler/SNANA#1374]
I am trying to simulate years 2-10 of LSST data. To do this, I changed only the GENRANGE_MJD and GENRANGE_PEAKMJD parameters in the input .yml file. 

I specified GENRANGE_MJD to be 61211 64398 and GENRANGE_PEAKMJD to be 61161 64448.

The simulation ran for 24 hours before abruptly cutting off, and never even completed the simulation stage. For reference, my outputs are in the following directory: /pscratch/sd/d/desctd/PIPPIN_OUTPUT/JP_LSST_BIASCORR_TEST01.

Thank you!

**Comment by RickKessler** [comment]
The problem is that you ran everything on just 1 CPU,
BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_SHIFTER_SHARED.TEMPLATE 1
and it exceeded the 24 limit,

tail -1 CPU0000_JOBLIST_login33.LOG 
slurmstepd: error: *** JOB 26759802 ON nid004120 CANCELLED AT 2024-06-15T00:30:45 DUE TO TIME LIMIT ***

Suggest using at least 10 cores (last arg of BATCH_INFO)

**Comment by jmpaulin** [comment]
Hello, I tried running with more cores as you suggested (I tried first with 10, then with 15) and the issue persisted. Is 10 years too long of a range to run at once? Am I changing everything correctly to try to run all 10 years? I changed GENRANGE_MJD and GENRANGE_PEAKMJD.
