### ISSUE TITLE
Simulation aborts with APPLY_SEARCHEFF_OPT: 5 despite SEARCHEFF_zHOST_FILE being provided

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#1376]
Encountering this abort error while trying to run Roman sims with a host redshift efficiency. 
`# ================================================
  PRE-ABORT DUMP from function check_APPLYMASK_SEARCHEFF :
         APPLY_SEARCHEFF_OPT += 1 --> detection pipeline.
         APPLY_SEARCHEFF_OPT += 2 --> SPEC confirmed.
         APPLY_SEARCHEFF_OPT += 4 --> zHOST.
         NONZERO_SEARCHEFF_SPEC=1   LSPEC=0
         NONZERO_SEARCHEFF_zHOST=1

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by check_APPLYMASK_SEARCHEFF
   Invalid user-input 'APPLY_SEARCHEFF_OPT: 5' (OVP=1)
   Simulation can produce SEARCHEFF mask 3`

SEARCHEFF_zHOST_FILE is specified, so not sure why APPLY_SEARCHEFF_OPT: 5 is not valid?

Error can be reproduced with: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/RC_ROMAN/1_SIM/ROMAN_BS20_mass/LOGS/FAIL_REPEAT_PIP_RC_ROMAN_ROMAN_BS20_mass_SNIaMODEL0-0001_53210.CMD`

**Comment by RickKessler** [comment]
This abort is due to a very old default in which EFF(spec) = 1.0 if the user does not specify a spec-Eff map file. Since you did not specify EFF(spec) map, the 100% spec-confirmed sample means that there are no zPHOT events, and thus APPLY_SEARCHEFF_MASK=5 is not possible. The simple fix is to add this into your sim-input file or command line arguments:
   SEARCHEFF_SPEC_FILE:   ZERO 

By explicitly setting EFf(spec) = 0, the zPHOT sample is well defined.
