### ISSUE TITLE
Ibn Precursor Model not Detected in 1YR LSST Sim

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#1377]
_Description:_  I've coded up a binary interaction-driven precursor model from this paper: https://arxiv.org/pdf/2406.12472. The model peaks at ~10^41 erg/s, so it should be bright enough to be detected by LSST, and it lasts 8 years. The light curve shape is very non-Ia-like, so we may have to play games in SNANA (lasts far longer than my sim window of 1yr, and it peaks at the END of the 8 years instead of the beginning) to get this to work.

_Directory:_ `/global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/agaglian/EruptivePrecursor`

_Command:_ `snlc_sim.exe SIMGEN_TEMPLATE_LSST_Ibn.INPUT`

**Comment by RickKessler** [comment]
To check what selection is applied,
grep APPLY SIMGEN_TEMPLATE_LSST_Ibn.INPUT
APPLY_SEARCHEFF_OPT:  1 #TURN OFF TO EVALUATE BINNING
APPLY_CUTWIN_OPT: 1 #TURNED OFF TO CHECK BINNING RECOVERY

So next we can run the sim with these APPLY commands disabled in order to get something written to the SIMGEN_DUMP file:

snlc_sim.exe  SIMGEN_TEMPLATE_LSST_Ibn.INPUT \
   NGEN_UNIT 0.01   APPLY_SEARCHEFF_OPT 0   APPLY_CUTWIN_OPT 0

To see the generated peak mags:
cd $SNDATA_ROOT/SIM/AGAG_LSST_1YR_IBN_NONCUTWIN

get_fitres_values.py -f AGAG_LSST_1YR_IBN_NONCUTWIN.DUMP \
   -v ZCMB,PEAKMAG_u,PEAKMAG_g,PEAKMAG_r,PEAKMAG_i,PEAKMAG_z \
   --nrow 10

# Read AGAG_LSST_1YR_IBN_NONCUTWIN.DUMP
# Found keyname_id = CID after skipping 6 rows
CID        ZCMB   PEAKMAG_u   PEAKMAG_g   PEAKMAG_r   PEAKMAG_i   PEAKMAG_z
  1 2.53982e-01 3.00876e+01 2.99317e+01 2.99392e+01 3.00390e+01 3.01477e+01
 10 1.25332e-01 3.27352e+01 3.26350e+01 3.25789e+01 3.26591e+01 3.27225e+01
  2 2.79654e-01 3.69161e+01 3.62178e+01 3.56006e+01 3.53356e+01 3.50840e+01
  3 2.90331e-01 3.07434e+01 3.04968e+01 3.04507e+01 3.04910e+01 3.05795e+01
  4 2.75297e-01 3.22594e+01 3.25759e+01 3.29460e+01 3.32454e+01 3.34803e+01
  5 2.84045e-01 3.32221e+01 3.33417e+01 3.35352e+01 3.37187e+01 3.38695e+01
  6 2.95887e-01 3.25394e+01 3.28236e+01 3.31588e+01 3.34430e+01 3.36592e+01
  7 1.77063e-01 3.28003e+01 3.28407e+01 3.29355e+01 3.30709e+01 3.31988e+01
  8 2.86770e-01 3.31060e+01 3.32575e+01 3.35082e+01 3.36977e+01 3.38818e+01
  9 2.56683e-01 3.36223e+01 3.27253e+01 3.21451e+01 3.17558e+01 3.16264e+01

which are all extremely faint, and thus always fails detection threshold.

**Comment by RickKessler** [comment]
If I generate in redshift range 0.007  to 0.013, about 20% of generated events are detected.
