### ISSUE TITLE
Model not recognized as NON1ASED

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#1387]
Hey Rick, I went through the steps to convert a model to NON1ASED so that I could simulate spectra and I'm getting an error that SNANA doesn't recognize it as a NON1ASED model. I've verified the model path. Any thoughts?

_Location on NERSC:_  `/global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/agaglian/ZTF_youngSNe/RUN_DIFFUSION`

_Command:_ `./SNIax.sh`

_Error:_ 
```
 ****************************************************************** 
   init_RateModel  

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by init_DNDZ_Rate
   DNDZ is specified, but found no NON1A SEDs.
   Remove DNDZ key or add NON1A SEDs.
```

**Comment by RickKessler** [comment]
The error message is not very clear. The problem is that SIMGEN_INCLUDE_SNIax.INPUT was missing these keys:

# added by RK, July 20 2024;
# index=0 is a flag to generate each index sequentially without  listing them all here.
NON1A_KEYS: 5 
         INDEX   WGT   MAGOFF  MAGSMEAR  SNTYPE
NON1A:    0      1.0    0.0     0.0        10

I added these keys to your INCLUDE file and sim runs. I also updated the error message to be more clear:
  "Add NON1A_KEYS and NON1A key(s) to sim-input file."
