### ISSUE TITLE
Fatal error using dust hostlibs

### ISSUE THREAD

**Issue by dscolnic** [RickKessler/SNANA#1413]
To reproduce:
[dscolnic@midway2-login2 dscolnic]$ pwd
/project2/rkessler/PRODUCTS/SNANA_DEBUG/dscolnic
(base) [dscolnic@midway2-login2 dscolnic]$ source test.cmd

 FATAL ERROR ABORT called by prep_dustFlags
   DO_AV=0 and DO_RV=2
   Must specify both AV & RV, or specify neither.

I think this issue is now - the hostlib has RV and EBV which is not usually a problem.
Thanks!

**Comment by RickKessler** [comment]
Your script is using a 3 year old snlc_sim.exe executable, so running current snlc_sim.exe fixes the AV abort problem. However, there is another problem with duplicate input keys in your input files ... snlc_sim used to allow duplicate input keys, but this led to lots confusion for code and humans, so the current code aborts on duplicate keys. I fixed a few duplicates in your input files (grep RK *.*), but you will need keep re-running test.cmd to find the next duplicate abort, and re-organize input files by figuring out which duplicate to keep/reject.

**Comment by dscolnic** [comment]
I use the new snlc_sim.exe and get the same error, thanks!

**Comment by RickKessler** [comment]
this is a subtle gzip bug that I have never been able to fix. When reading a gzip file, rewind causes a rare corruption and thus rewind is not used for gzip files. Even closing and re-opening the gzip file can cause corruption. For GENPDF_FILE, the snana_open command searches for DOCUMENTATION block on first line, but doesn't find it because VARNAMES is on the first line in this particular gzipped GENPDF_FILE. Without the rewind, the remainder of the read-code does not find the first VARNAMES that was already ready while looking for the DOCUMENTATION key.

The simple solution here is to gunzip the GENPDF_FILE (which I did), and the code goes past the previous abort. A more robust solution is to add a DOCUMENTATION block at the top of the file.

The test.cmd job still aborts with a different error:

 FATAL ERROR ABORT called by ENDSIMLIB_check
   Could not find SIMLIB HEADER passing GENRANGE_XXX cuts.
   Check USE_SIMLIB_XXX flags and header values.

**Comment by dscolnic** [comment]
Thanks - the .gz was the main issue!
