### ISSUE TITLE
Allow VERSION_PHOTOMETRY to work with a full path

### ISSUE THREAD

**Issue by mattgrayling** [RickKessler/SNANA#1414]
I am running some fits on data in a private location using submit_batch_jobs, which is being used to call BayeSN, but PRIVATE_DATA_PATH doesn't seem to be working in this mode. Could I request that a change be made to submit_batch_jobs so that the code will still run if a full path is used for VERSION_PHOTOMETRY, rather than just the name of a directory?

**Comment by RickKessler** [comment]
I'm going to hold off on this update because I worry about introducing lots of bugs. Short-term, please add analogous PRIVATE_DATA_PATH key to BayeSN fitter because this is easy to integrate into submit_batch_jobs.

As a reminder, the original concept was that data (real and sim) are in well-defined places that the analysis codes (and SNANA users) know how to find, and to avoid a proliferation of data folders that get lost or become hard to find. Sim data must reside under $SNDATA_ROOT/SIM or in one of the paths listed in $SNDATA_ROOT/SIM/PATH_SNDATA_SIM.LIST. Real data must reside under $SNDATA_ROOT/lcmerge or under user-defined PRIVATE_DATA_PATH arg.
