### ISSUE TITLE
Issue running snlc_sim.exe

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#144]
In 
/project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/STEVE_SPECS/DEMOSv1

Tried running 
snlc_sim.exe SIMGEN_WFIRST_COSMOS_DEIMOS_SPECSIM.INPUT

Received error 
    Begin Generating Lightcurves.   

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by GENSPEC_LAMSMEAR
   NLAMSMEAR = 20 exceeds bound of 20
   ilam=0 LAMAVG=5380.32

**Comment by srodney** [comment]
For context: Rebekah and I are simulating host galaxy spectra here. 

I think I may have a handle on this.   There's a default parameter NLAMSIGMA that can be overwritten by the spectrograph file (I think).  It is set to 5.0.   Now that our  new DEIMOS spectrograph file has a much smaller 'pixel scale' of 0.65 Angstroms/pixel (really, the size of a wavelength bin in the spectrograph file), we get a patch of code in snlc_sim.c trying to bin up more than 20 wavelength bins, which trips the abort.

possible solution is to set NLAMSIGMA to an integer less than 4.

**Can we just add this line to the header section of the spectrograph file? :**
NLAMSIGMA:   3

although I think we actually want no binning in the spectral direction, which I guess is accomplished by
NLAMSIGMA: 1

I think this function was designed for simulating SN spectra, which is why there's a healthy default binning built in.

**Comment by RickKessler** [comment]
extended max number of LAMSMEAR bins from 20 to 40, and reduced +_5 sigma integration to +-3 sigma. Please consider rebinning the spectrograph by a few (but still with binSize < 3.5 sigma resolution) so that sim jobs run faster and with less memory.
