### ISSUE TITLE
WGTMAP VARNAMES

### ISSUE THREAD

**Issue by benjaminrose** [RickKessler/SNANA#1444]
I am trying to add `$SNANA_ROMAN_ROOT/simlib/WGTMAPS/ELASTICC_SLSNI_GHOST.WGTMAP.gz` to a set of existing simulations. Simulations run fine without it but when the WGTMAP is added fails with the following error: 

```
Read WGTMAP VARNAMES from file:
        /project2/rkessler/SURVEYS/ROMAN/ROOT/simlib/WGTMAPS/ELASTICC_SLSNI_GHOST.WGTMAP.gz
        NDIM = 2 NFUN = 2
         replace LOGMASS_TRUE colummn with  LOGMASS
         replace LOGSFR_TRUE colummn with  LOGSFR
         Load 'ZTRUE,logsfr,LOGMASS_TRUE,LOGSFR_TRUE' for SNTABLE storage.
  Read entire WGTMAP file:
        /project2/rkessler/SURVEYS/ROMAN/ROOT/simlib/WGTMAPS/ELASTICC_SLSNI_GHOST.WGTMAP.gz
        NDIM = 2 NFUN = 2
    Load GRIDMAP-020 'WGTMAP(LOGMASS,LOGSFR)'  NROW=178296
         malloc_GRIDMAP: allocate 3.57 MB for 178296 bins
         replace LOGMASS_TRUE colummn with  LOGMASS
         replace LOGSFR_TRUE colummn with  LOGSFR
         Ignore SNMAGSHIFT in WGTMAP
         Reading /project2/rkessler/SURVEYS/ROMAN/ROOT/starterKits/sim_host_redshift/3dhst_sim_input_cat_v1.7_BMR.hostlib
         replace LOGSFR_TRUE colummn with  LOGSFR
         replace LOGMASS_TRUE colummn with  LOGMASS

...

 FATAL ERROR ABORT called by read_head_HOSTLIB
   Could not find required HOSTLIB var 'logsfr' (IVAR_STORE=2)
   Check HOSTLIB VARNAMES, WGTMAP & HOSTLIB_STOREPAR key.
```

The WGTMAP file has keys `VARNAMES_WGTMAP: LOGMASS LOGSFR WGT SNMAGSHIFT` and the HOSTLIB has keys that include `ZTRUE ZERR LOGSFR LOGMASS logssfr`.

Why is SNANA looking for `logsfr` when the lower case version is a variable in either the WGTMAP or HOSTLIB?

----

Outputs can be found at `$PIPPIN_OUTPUT/PIPPIN_ROMAN_TRANS/1_SIM/ROMAN_PLAsTiCC_SLSN` and created with `$NGRST_USERS/brose3/roman/PIPPIN_ROMAN_TRANS.yml`.

**Comment by benjaminrose** [comment]
The failure can be repeated with `$PIPPIN_OUTPUT/PIPPIN_ROMAN_TRANS/1_SIM/ROMAN_PLAsTiCC_SLSN/LOGS/FAIL_REPEAT_PIP_PIPPIN_ROMAN_TRANS_ROMAN_PLAsTiCC_SLSN_NONIaMODEL0-0001_33680.CMD`

**Comment by RickKessler** [comment]
The missing HOSTLIB variable is because   "logsfr" is in the SEARCHEFF_zHOST_FILE file, but logsfr is not in the HOSTLIB. This is a tricky abort to track that has caused problems in the past, so I made two diagnostic updates to the stdout. First, each appended "STOREPAR" variable is printed to stdout:
  append HOSTLIB_STOREPAR with ZTRUE from SEARCHEFF_zHOST_FILE
  append HOSTLIB_STOREPAR with logsfr from SEARCHEFF_zHOST_FILE
  append HOSTLIB_STOREPAR with LOGMASS,LOGSFR from HOSTLIB_WGTMAP_FILE

Second, the abort message includes a more comprehensive list of maps to check for sources of required HOSTLIB variables:
 FATAL ERROR ABORT called by read_head_HOSTLIB
   Could not find required HOSTLIB var 'logsfr' (IVAR_STORE=2)
   Check HOSTLIB_STOREPAR key and VARNAMES in HOSTLIB, GENPDF, zHOST, WGTMAP files.
