### ISSUE TITLE
filter name issue when simulate light curves

### ISSUE THREAD

**Issue by qnwang93** [RickKessler/SNANA#1446]
I try to run simulation on the NERSC server using commands like:

`snlc_sim.exe JLA_TRAINING_SNLS3.INPUT`

In the generated light curves, the band names are the last characters of band names in kcor files, instead of the full band name. That cause those light curve files unreadable by trainsalt. Attached are the simulation input and kcor files I used.
[JLA_TRAINING_SNLS3.INPUT.txt](https://github.com/user-attachments/files/17820378/JLA_TRAINING_SNLS3.INPUT.txt)
[kcor_SNLS.fits.zip](https://github.com/user-attachments/files/17820382/kcor_SNLS.fits.zip)

**Comment by RickKessler** [comment]
please provide path and command to run on Perlmutter@NERSC.

**Comment by qnwang93** [comment]
I was running command `snlc_sim.exe JLA_TRAINING_SNLS3.INPUT` in my personal directory`/global/homes/q/qnwang/`. Do you have access to that? Or maybe I could make a copy in some common directory?

**Comment by RickKessler** [comment]
A long time ago I updated SNANA to read/write full filter names in data, but still keep single char for sims in order to avoid increasing disk space. Here I updated code again to write full filter names for sim as well as for data. Also added MXCHAR string length check on both FILTER name and FIELD name to avoid memory overwrite (both allowed up to 20 chars).
