### ISSUE TITLE
zerr_adjust 

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#193]
```
cd /project2/rkessler/PRODUCTS/SNANA_DEBUG/SALT2mu_SUBPROCESS
SALT2mu.exe SALT2mu_DESNN_SIM.input 
```

produces the following error

```
# ================================================ 
  PRE-ABORT DUMP from function zerr_adjust : 
   sqzerr[1,2,3] = 1.988100e-06, 1.997608e-06, 1.994845e-10 
   zpecerr_user = 0.000010 
   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    
 FATAL ERROR ABORT called by zerr_adjust
   sqrt(negative number); Cannot adjust zHDERR
   Check pre-abort dump above.
```

**Comment by RickKessler** [comment]
input file has pecv=0.00001, corresponding to 3km/sec. This is an override command, so it subtracts out the already-defined 300 km/sec error (in quadrature), and adds bad 3km/sec in quadrature ... but the quadrature sum is negative, so it fails. I would recommend removing this ancient pecv input since zHDERR seems to already include peculiar-velocity error.
