### ISSUE TITLE
does BBC work with perfect sims?  getting intrinsic dispersion error

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#202]
Hi Rick, quick BBC error with perfect simulations.  By running
```
cd $SNANA_DEBUG/djones/BBC2
SALT2mu_fit.pl BBC.input.temp.1597418095.606237_131
```
I get the error message
```
 ****************************************************************** 
    makeSparseList_biasCor: make sparse row-list for each biasCor sample.  
 init_sigInt_biasCor_SNRCUT for all IDSAMPLEs combined: 
	 sigInt[ia,ib,ig=0,0,0] = 0.0981 (28184 events with SNR>30) 
   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    
 FATAL ERROR ABORT called by init_sigInt_biasCor_SNRCUT
   Avg computed muErr > RMS(mures) for SNRMAX>30
   <muErr>=0.098149   RMS(mures)=0.085688   ia,ib,ig = 0,1,0
```
I tried to fix sigint to zero but it didn't help.  Do you know what's going on?  Thanks!

**Comment by mi-dai** [comment]
got a fix by changing the following in the BBC input but not sure if it's actually the right way.  
```sigint_biascor=0
#snrmin_sigint_biascor=30 # SNRMIN to compute siginit_biascor```

**Comment by RickKessler** [comment]
default snrmin_sigint_biascor=60, so removing the line above just reverts to default. The more important change (above) is forcing sigint_biascor=0 so that the calculation is skipped. For perfect sims that have no intrinsic scatter, sig_int should be 0, but the brute force calculation could end up with a variance that is slightly negative due to random fluctuations. In short, your fix above is correct.
