### ISSUE TITLE
BBC missing a significant fraction of biascor for a biascor sim with million+ objects

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#230]
Hi Rick,

I got warnings in the SALT2mu FITRES file like below:

`# WARNING(SEVERE): 129 of 424 events (30.4 %) have no biasCor for CFA3S+CFA3K+CFA4p1+CFA4p2`
`# WARNING(SEVERE): 36 of 868 events (4.1 %) have no biasCor for PS1MD`

the biascor sims have size of ~a million (a bit smaller after cuts). I can possibly get rid of the PS1MD warning by increasing the sim size a bit more, but the lowz sample is always missing ~30% when I was trying even larger biascor sims.

An example is in `$SNANA_DEBUG/mdai/BBC_missing_biascor`
I was running `SALT2mu_fit.pl BBC.input` (the lcfits were generated with old scripts so don't seem to work with the new submission script)

Thanks!

**Comment by RickKessler** [comment]
plotting zHD, all but one of the lost low-z events has zHD>0.07. The reason is that the biasCor for each event must be interpolated from a lower- and higher-redshift bin. Thus if zMax for data and sim is the same, the last data bin is dropped ... in this case, the data bin 0.07 to 0.09 is dropped. To get this last bin, generate the biasCor out to 0.09, and change biasCor bin size from 0.02 to 0.01.
