### ISSUE TITLE
header_override_file string length

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#245]
Hi Rick, Now that you're allowing multiple header override files (in lcfitting) to be included in a comma separated list, I suspect I'm exceeding the maximum string length. Can I ask you to open this up (a lot!)?

```# ================================================ 
  PRE-ABORT DUMP from function TABLEFILE_OPEN : 
  file=
 /project2/rkessler/SURVEYS/PS1MD/USE

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by TABLEFILE_OPEN
   Unknown table-file type
   STRINGOPT = 'read' 
```

**Comment by RickKessler** [comment]
Please provide example to reproduce error. Not sure if problem is string length, or limit on number of files. I had mistakenly left out check on MXFILE_LIST, so I added the missing abort trap but didn't change any limits. Will check later when abort-example is provided.

**Comment by djbrout** [comment]
debug example here
`$SNANA_DEBUG/djbrout/headeroverride/RUNTEST`

**Comment by RickKessler** [comment]
I fixed snana.exe,snlc_fit.exe to abort when requested HEADER variables are not valid ... previously it aborted only if first file in HEADER_OVERRIDE list was invalid; now it checks each file. For the new abort, it prints a full list of valid HEADER_OVERRIDE variables, and also prints variables in your HEADER_OVERRIDE file; this should make it easier to fix names, types, etc.

Here are issues/fixes for your OVERRIDE files:

* HOSTGAL_SFR.txt fails because HOSTGAL_SFR is not valid;
  instead, use HOSTGAL_sSFR

* HOST_LOGMASS_ERR.txt fails because
  HOST_LOGMASS_ERR should be HOSTGAL_LOGMASS_ERR
   [also, remove NVAR key]

* HOST_SFR_ERR.txt fails because HOST_SFR_ERR is not valid;
   instead, use HOSTGAL_sSFR_ERR

Lastly, please check if override works properly for all variables when using multiple override files. The provided DEBUG job only shows an override for one variable (LOGMASS),
so I could not check that other variables are working.
