### ISSUE TITLE
SNANA not passing SN Host redshift to BYOSED

### ISSUE THREAD

**Issue by jpierel14** [RickKessler/SNANA#276]
Debug example in `$SNANA_DEBUG/BYOSED_Redshift`, using the older version of SNANA that I'm running sims with. I believe `genmag_PySEDMODEL.c` is the same though, so the update should be the same in both places. Running the `runtest.sh` file in the debug folder sources the BYOSED_dev3 sourceme, and runs the sim. I have it printing what BYOSED receives as host parameter names, and the host parameter array when getting the flux for a given phase. It errors because redshift is never updated, so it's of `NoneType` which causes an error.

**Comment by djones1040** [comment]
hi Rick, now that I've done a fresh clone of BYOSED, it's probably time to fix the other outstanding error I was supposed to send you an issue about.  Justin's command above will now produce a new error:
```
 FATAL ERROR ABORT called by init_genmag_PySEDMODEL
   Could not import module gensed_
   2nd message ??
```
what's happening here is that SNANA has the model listed as an empty string so it's trying to import "gensed_" instead of "gensed_BYOSED"

**Comment by RickKessler** [comment]
for 2nd issue, GENMODEL argument must include BYOSED or SNEMO ; e.g., 
GENMODEL:  [mypath]/BYOSED.XYZ
GENMODEL: [mypath]/SNEMO.ABC
I had left a code message for myself to abort if no model is found, but I forgot about it, which is why it wasn't aborting. The abort sequence has been added.

**Comment by RickKessler** [comment]
above is fixed to use explicit MODEL_NAME, so path name doesn't matter.
