### ISSUE TITLE
SALT2mu VPEC error from simulations

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#284]
Hi Rick,

Got one more for you.  This is a little slow to run, but the following set of commands fails because of the new VPEC abort trap in SALT2mu (even though all of these data are simulated).

```
cd $SNANA_DEBUG/djones/salt3sim2
snlc_sim.exe JLA_TRAINING_Hicken09_G10.INPUT
snlc_fit.exe snfit_Hicken_G10.NML
SALT2mu.exe SALT2mu.default file=JLA_TRAINING_Hicken09_LARGE_G10.FITRES.TEXT
```

The error is:

```
 check_vpec_sign with RMS(MURES) using N(0.010<z<0.050) = 30 events:
	 RMS(MURES,nominal)   = 0.1163
	 RMS(MURES,flip-vpec) = 0.1146

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by check_vpec_sign
   RMS(MURES) is smaller with vpec sign-flip.
   See RMS(MURES) values above.
```

**Comment by RickKessler** [comment]
there are very few events for z < 0.05, so I'm wondering if this a stat fluctuation. Can you generate xfew more ? Also, check manual 4.30.1 Generating Peculiar Velocity; you have defined physical GENSIGMA_VPEC=150 as the true scatter, but since you didn't define VPEC_ERR, the simulated measurement error is zero -> perfect measurement of VPEC. Note that VPEC=SIM_VPEC in your FITRES file. Not sure if VPEC_ERR=0 was your intention, or an oversight.

**Comment by djones1040** [comment]
hi Rick - it could be a statistical fluctuation, but SNANA should not break just because I'm generating small simulations; small simulations are very useful!  I can add a VPEC error term and see if that fixes things.

**Comment by RickKessler** [comment]
as a temp fix, the vpec-flip test requires at least 70 events (was 10). May need sim tests to figure out appropriate statistics. Regardless of stats, the vepc-flip test can be disabled with 
    zwin_vpec_check=0,0
