### ISSUE TITLE
Different PKMJDINI methods in single nml

### ISSUE THREAD

**Issue by anaismoller** [RickKessler/SNANA#290]
Option to output different PKMJDINI determination methods using a single nml file. 
e.g.

File 1: Standard configuration with
OPT_SETPKMJD = 16

FIle2: Reject non-detection with large SNR
PHOTFLAG_DETECT   = 4096
CUTWIN_SNR_NODETECT = -100, 10

File3:  season edge improvement
OPT_SETPKMJD = 32

File4: season+non detection
OPT_SETPKMJD = 32
PHOTFLAG_DETECT   = 4096
CUTWIN_SNR_NODETECT = -100, 10

**Comment by RickKessler** [comment]
The above is easy to do with command line overrides:
snana.exe <myInput> OPT_SETPKMJD=16   TEXTFILE_PREFIX=out1
snana.exe <myInput> PHOTFLAG_DETECT=4096  CUTWIN_SNR_NODETECT=-100,10  TEXTFILE_PREFIX=out2
snana.exe <myInput> OPT_SETPKMJD=32 TEXTFILE_PREFIX=out3
snana.exe <myInput> OPT_SETPKMJD=32  PHOTFLAG_DETECT=4096 CUTWIN_SNR_NODETECT=-100,10 TEXTFILE_PREFIX=out4

Note that key=value syntax is a recent syntax upgrade so that command line args look more similar to the input file syntax. But beware that no pad spaces are allowed when using equal signs, and multiple values must be comma-separated with no pad spacing. You can also use the original syntax with spaces, e.g.,
   snana.exe <myInput> OPT_SETPKMJD 16   TEXTFILE_PREFIX out1

**Comment by anaismoller** [comment]
Thanks!
