### ISSUE TITLE
include full filter names in lightcurve data files

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#330]
Hi Rick, as discussed in the SALT3 meeting, this is just a request to include the full filter names in lightcurve data files so when we do these big merged low-z versions we can easily tell which filters are BVRI for example.  Thanks!

**Comment by RickKessler** [comment]
There are 2 updates for this request. First, snana can now read TEXT data files where the filter name is a string; e.g, CFA3-U is read internally as U, etc ... There is no change to FITS format where filters are described by single char. Second change is in "combine_dataVersions.py" that outputs the full filter names in the TEXT data files; e.g., 'CFA4K/l' instead of just 'l'. This change is for human readability and has no effect on the code execution.
