### ISSUE TITLE
Replace the addition approximation for peculiar velocity

### ISSUE THREAD

**Issue by bcarreres** [RickKessler/SNANA#369]
Hi,
As we talk yesterday, is it possible to replace the approximation z+=z_pec by z = (1+z)(1+z_pec) -1 ?

Thanks you !

**Comment by RickKessler** [comment]
Good catch. A few years back I fixed VPEC correction in the analysis and BBC codes ... but forgot about the sim. Should be fixed now using exact formula. Pushed to Github, Midway and NERSC.

**Comment by RickKessler** [comment]
FOLLOW-UP: here is a crosscheck on a low-z sim with GENSIGMA_VPEC: 300 and VPEC_ERR: 0 so that the VPEC correction is perfect. With the previous VPEC approximation in the sim, zHD in the SNANA table does not quite match the true SIM_ZCMB because analysis codes use exact VPEC formula while sim used approximation. Resulting zHD-SIM_ZCMB difference of ~E-4. Using fixed simulation, zHD = SIM_ZCMB as expected.
<img width="722" alt="sim-vpec_test" src="https://user-images.githubusercontent.com/24592476/106150034-87dad980-6140-11eb-9b11-74f42e301b5d.png">
