### ISSUE TITLE
Attempts at 1D bias corrections crashing.

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#38]
Hi Rick!

I'm trying to make a 1D biascor sim. 
if I run 
/project2/rkessler/SURVEYS/SDSS/USERS/BAP37/MASS_paper/BBC7D_Test/SIMGEN_SNIa+G10_1D.INPUT

it'll run just fine, but putting it together in a big simulation, 

/project2/rkessler/SURVEYS/SDSS/USERS/BAP37/MASS_paper/BBC7D_Test/SIMGEN_MASTER_BIASCOR_1D.INPUT

I get some weird errors - 
/project2/rkessler/SURVEYS/SDSS/USERS/BAP37/MASS_paper/BBC7D_Test/SIMLOGS_DES_BIASCOR_1D/

Any given file in there has an error.

FATAL ERROR ABORT called by snfitsio_errorCheck                                             
  fits_write_col for PHOT-param: ZEROPT                                                 
  Check cfitsio routines.

Thanks!

**Comment by RickKessler** [comment]
works fine for me. Best guess is that your scratch quota is exceeded. I also noticed you have "OPT_DEVEL_BBC7D 0". I would recommend removing this because it will be removed in the near future, and it's no longer supported. If you think it's necessary to go back to the older method, please let me know why.
