### ISSUE TITLE
Unusual gen_zsmear issue 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#387]
Getting the following error: 

 FATAL ERROR ABORT called by gen_zsmear                                                                                                           
   Could not generate random Z after 10 tries                                                                                                     
   Each Z < ZGEN_MIN = 0.000100  z[cmb,hel]=0.002495,0.000023)  

Inside of 

/scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-HALO-CMB/1_SIM/LOWZ_DATA/LOGS/FAIL_SUMMARY.LOG

The original file is here: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/VPEC/BP-HALO-CMB.yml

**Comment by RickKessler** [comment]
There were 2 issues. First, there were a few places in the sim where VEL_CMBAPEX=0 was ignored; I fixed these. Second, and more importantly, there are HOSTLIB entries where
     ZTRUE + VPEC/c < 0.
The resulting negative zHELIO is also known as a blue shift. Since I am not aware of blue shifted SNe, I added a safe option of aborting if any HOSTLIB galaxy satisfies 
    ZTRUE + VPEC/c < 0.001. 
The first abort from your sim job is from a more-than 3 sigma VPEC outlier: 

  PRE-ABORT DUMP from function sortz_HOSTLIB : 
	 ZTRUE(HOSTLIB) = 0.003009 
	 VPEC(HOSTLIB)  = -960.221000 
	 ZMIN_HOSTLIB   = 0.001000 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by sortz_HOSTLIB
   ZTRUE + VPEC/c = -0.000194  < 0.001000
   Fix HOSTLIB VPEC or increase GENRANGE_REDSHIFT[0] > 0.003000
