### ISSUE TITLE
negative redshift issue

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#415]
some candidates in SDSS have -9 for redshift
I have a cutwin in my nml file to protect for this but it doesnt seem to be filtering.
Example CID=722

`$SNANA_DEBUG/djbrout/SDSS/RUNME`

**Comment by RickKessler** [comment]
I made a little min script to illustrate after translating back to TEXT format:

./RICK_REFORMAT
SDSS_DS17 
REDSHIFT_HELIO:   0.086341 +- 0.000036  # Helio 
REDSHIFT_FINAL:   -9.000000 +- -9.000000  # CMB (no VPEC corr) 
 
SDSS_allCandidates+BOSS (ORIGINAL)
REDSHIFT_HELIO:   0.086341 +- 0.000036  # Helio 
REDSHIFT_FINAL:   0.085038 +- 0.000036  # CMB (no VPEC corr) 

The original SDSS data file has both REDSHIFT_HELIO and REDSHIFT_FINAL(CMB). However, the hacked DS17 version only has REDSHIFT_HELIO ... which is enough since the code computes REDSHIFT_CMB internally.

**Comment by djbrout** [comment]
Brodie (my resident SDSS redshifts expert) says there is no REDSHIFT_FINAL column in the RICK_REFORMAT. So how are you finding REDSHIFT_FINAL there?

**Comment by RickKessler** [comment]
cd /project2/rkessler/PRODUCTS/SNANA_DEBUG/djbrout/SDSS/SDSS_DS17_TEXT
grep REDSHIFT SDSS_DS17_TEXT_722.DAT 
REDSHIFT_HELIO:   0.086341 +- 0.000036  # Helio 
REDSHIFT_FINAL:   -9.000000 +- -9.000000  # CMB (no VPEC corr)

**Comment by bap37** [comment]
There's no REDSHIFT_FINAL column in /project2/rkessler/SURVEYS/PS1MD/USERS/dscolnic/PANTHEON+/lcmerge/JLA2014_SDSS_DS17/JLA2014_SDSS_DS17_HEAD.FITS
which is what's being fitted - so where is the REDSHIFT_FINAL value being drawn from? In that FITS there is a REDSHIFT_HELIO and REDSHIFT_CMB, neither of which are -9.

**Comment by RickKessler** [comment]
SNANA code fixed to read either REDSHIFT_FINAL or REDSHIFT_CMB

**Comment by RickKessler** [comment]
REDSHIFT_CMB is now computed from REDSHIFT_HELIO ... for TEXT format ... to allow quickly made data files from surveys.
