### ISSUE TITLE
SNANA SALT2 fits crashing

### ISSUE THREAD

**Issue by anaismoller** [RickKessler/SNANA#431]
SALT2 fit on data crashes due to:

" Excerpt:    FATAL ERROR ABORT :                                                                                                        
[   ERROR |           manager.py:427]           Excerpt:       Found 2492 events in merged MERGE_DESALL_forcePhoto_real_snana_fits_FITOPT000.ROOT                                      
[   ERROR |           manager.py:427]           Excerpt:       but expected 2753 from summing YAML files.                                                                              
[   ERROR |           manager.py:427]           Excerpt:       Table merge has a problem.                                                                                              
[   ERROR |           manager.py:427]           Excerpt:       Check CPU0000*.LOG for merge crash "

But the splits seem to have run succesfully `$PIPPIN_OUTPUT/AM_DATA5YR/2_LCFIT/D_DATA5YR_DENSE_SNR/output`

**Comment by RickKessler** [comment]
this was a really evil bug. There is a check on whether SNHOST_SB__FLUXCAL exists that determines if it goes into the output tables. However, I had mistakenly made the check assuming mag (SBFLUX < 99 ==> exists) instead of FLUXCAL. In rare cases, the first event has a really bright SB where all bands have SB_FLUXCAL > 99, so the code incorrectly sets the EXIST flag to false and excludes HOST_SB from output table. If all ROOT tables but one have SB_FLUXCAL columns, the merge process fails.

It's fixed.
