### ISSUE TITLE
DAT to FITS conversion is busted

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#441]
/scratch/midway2/rkessler/PIPPIN_OUTPUT/PS1-DATA-CLASS/3_CLAS/SNNTEST_PS_DATAPS1_SNNTEST_PS_PS1-MVCC/output.log
OSError: Header missing END card.   

SNN is reporting that the FITS header is missing an END card when trying to convert dat to FITS - /project2/rkessler/PRODUCTS/SNANA_DEBUG/Brodie/convert_text_to_fits

**Comment by RickKessler** [comment]
The SNANA codes can read the FITS formatted output, but since SNN is not an SNANA code, may need to contact Anais. However, I noticed two issues. First, the output table from snana.exe still wrote FIELD = NULL, so I fixed it to write FIELD = VOID. Second, the input TEXT data files have lots of NaN, which may cause parsing problems for SNN. I updated the SNANA code to check NaN in the TEXT data files, so trying to convert TEXT -> FITS now results in

 FATAL ERROR ABORT called by RD_SNTEXTIO_EVENT
   Found 161 NaN errors for CID=PS0909006
   Fix your TEXT formatted data files

**Comment by RickKessler** [comment]
Gonna close this issue for now; re-open later if needed.

**Comment by bap37** [comment]
SNANA can read in the recently created FITS files, but reports them as being entirely empty. Furthermore, the SNN issue isn't a specific implementation created by Anais, but rather astropy not finding an END: card in the FITS file itself. I'm pretty sure these two are related.

/scratch/midway2/rkessler/PIPPIN_OUTPUT/PS1-DATA-CLASS/2_LCFIT/PS1FIT_DATAPS1/output/SPLIT_JOBS_LCFIT

**Comment by bap37** [comment]
Double checking, it looks like the FITS_HEAD file is entirely empty or otherwise formatted in a way that is unreadable - all the entries are empty.

**Comment by RickKessler** [comment]
The HEAD file for PS1_PS1MD_cen_SIGCLIP_FITS_HEAD.FITS is empty; you need to go back and check how this data version was created.

**Comment by bap37** [comment]
It was created by SNANA from /project2/rkessler/PRODUCTS/SNANA_DEBUG/Brodie/convert_text_to_fits

**Comment by RickKessler** [comment]
check convert.log:
 FATAL ERROR ABORT called by RD_SNTEXTIO_EVENT
   Found 135 NaN errors for CID=PS0910012
   Fix your TEXT formatted data files

So not surprising that the FITS files are empty.

**Comment by bap37** [comment]
Yes - I addressed this in slack, every file has all sorts of NaNs in the FLUX column. Is there any way to get SNANA to ignore the FLUX, or am I going to have to manually convert these files?
