### ISSUE TITLE
zmin option in SALT2mu not applied

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#451]
submit_batch_jobs.sh $SNANA_DEBUG/rebeccachen/RC_DATA_BBC.input

Error:   - FATAL ERROR ABORT called by compute_more_TABLEVAR
  - Invalid DATA redshift = -0.000390
  - for ISN=44, SNID='1446086'

Gives negative redshifts for fitopts that use SN z fit. I think this is because somehow a redshift of 0 is fit for SNID='1446086'. I have zmin=0.01 in the input file, so I'm not sure how it is getting through.

**Comment by RickKessler** [comment]
This event has ZHEL=0 and zCMB<0 ?? Can you trace back the sim job which produced this event so I can check why this event didn't get rejected or cause an abort ? The SALT2mu abort-check is applied before cuts ... negative redshifts should not be ignored because the underlying cause might impact the z>0 sample as well.

I also noticed that many of your BBC jobs failed because of the VPEC sign-flip test. Not sure what's going on here, but the mean <VPEC> is notable away from zero.

**Comment by rebeccachen0** [comment]
The fit is from here /scratch/midway2/rkessler/PIPPIN_OUTPUT/RC-G10-DESLOWZX5/2_LCFIT/DATAFIT_DATA_DES5YR/output/DESALL_forcePhoto_real_snana_fits

Of the 6 FITOPT, only the 3 with DOFIT_PHOTOZ T (002, 003, 005) are ending up with z=0. The others have a normal redshift. I'm not sure why this is the only SN with this problem.

**Comment by RickKessler** [comment]
Try setting PHOTOZ_BOUND to something like 
FITOPT:   PHOTOZ_BOUND .01  1.5 [etc ...]
and also study simulated samples to characterize catastrophic outliers.
