### ISSUE TITLE
SIM_SEARCHEFF_MASK returning 0 and 3

### ISSUE THREAD

**Issue by pmacias** [RickKessler/SNANA#498]
Hi Rick,

When I run the full production runs of ALT04:

cd /project2/rkessler/SURVEYS/WFIRST/USERS/pmacias/dev/pippin
pippin.sh WFIRST_starterKit+ALT04.yml

I get mostly 0 values and some 3 and 5 for SIM_SEARCHEFF_MASK in the DUMP files
![image](https://user-images.githubusercontent.com/4205149/120047845-7ad4d680-bfca-11eb-9265-45cba19054dd.png)

however, when running smaller test sims with 

cd /project2/rkessler/SURVEYS/WFIRST/USERS/pmacias/dev/sim
snlc_sim.exe SIMGEN_WFIRST_Allz_SNIA.input

I get no 3 values, only 0 and 5 (whether we are pointing to SEARCHEFF_SPEC_ZERO.DAT or setting SEARCHEFF_SPEC_SCALE = ZERO) : 

![image](https://user-images.githubusercontent.com/4205149/120048508-25012e00-bfcc-11eb-9b84-d0e13355e3be.png)

I'm not sure why we are getting no "1" values in any of the DUMP files. Any help would be appreciated. Thanks!

-Phil

**Comment by RickKessler** [comment]
so two issues; one benign, one important. 
Important: MASK=3 is likely from CC sim because there is no SPEC_FILE and thus EFF_SPEC=1.0 by default. Requiring MASK=5 might explain the surprisingly small CC contamination.  Need to set EFF_SPEC=0 for CC too.

The benign issue is lack of MASK=1 events. I had forgotten about a speed-up trick in which EFF_zHOST is evaluated and applied before the light curve is generated or digitized. Thus we don't get MASK=1 in the output.
