### ISSUE TITLE
LAMBDA_RANGE error in sims

### ISSUE THREAD

**Issue by geotaylo** [RickKessler/SNANA#536]
I am trying to simulate the JLA training sample using the JLA-B14 SALT2 model and am getting the following error:

  PRE-ABORT DUMP from function interp_primaryFlux_SEDMODEL :
         Expected lam-range: 12580.0 - 12600.0 A  ilam=1049/1051 .

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by interp_primaryFlux_SEDMODEL
   lam=12602.8 is outside expected range
   Check LAMBDA_RANGE key in kcor-input file.
   
   I'm not sure why this is occurring/what the most appropriate fix is?
   
   Logs are in $DES_USERS/gtaylor/SNANA_SIMS/what_the_spec/SIMLOGS_GT_TEST_JLA/

**Comment by RickKessler** [comment]
what is $SALT3TESTS_DATADIR ?

**Comment by RickKessler** [comment]
<img width="743" alt="snana-abort" src="https://user-images.githubusercontent.com/24592476/122615094-8b1e2580-d04d-11eb-800a-c6977f0aa3cd.png">

I have fixed the sim to give a proper abort message (see attachment). The issue is that the spectrograph wave range goes just outside the primary SED range, where the primary is defined in kcor file. Another subtle issue is that the spectrograph wave range is internally extended (based on wave resolution) in order to properly account for wave-smearing near the edges. In your sim job, it adds one more wave bin, which brings the range just outside  the 12600 A range of the primary SED. The simple fix is to trim the spectrograph wave range by few tens of A, and remake the kcor-input file.

**Comment by geotaylo** [comment]
I've commented out the last two entries in the spectrograph file and remade the kcor file, and now the sim is crashing...  output in /project2/rkessler/SURVEYS/DES/USERS/gtaylor/SNANA_SIMS/what_the_spec/JLA/SIMLOGS_GT_TEST_JLA

**Comment by RickKessler** [comment]
export SALT3TESTS_DATADIR=$SNTRAIN_ROOT/SALT3_training_tests

**Comment by RickKessler** [comment]
fixed bug introduced late May, related to reading TAKE_SPECTRUM keys from SIMLIB header. I checked that sim runs without crashing, but didn't check output.

**Comment by djones1040** [comment]
hey Rick, weighing in here - here's how to reproduce the error:
```
cd $SNANA_DEBUG/djones/kcor
# create the kcor file
kcor.exe kcor_JLA_LOWZ_COMBINED.input
# run the sim
snlc_sim.exe JLA_TRAINING_COMBINED_LOWZ.INPUT
```
I'm not sure what this error means either - it's pretty unclear what SNANA expects from these spectrograph files

**Comment by geotaylo** [comment]
Output looks to be as expected now, thanks!
