### ISSUE TITLE
SALT2mu_SUBPROCESS output a fitres 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#538]
An option within the SUBPROCESS feature to provide a fitres with the GENPDF reweight for debugging purposes would be wonderful!

**Comment by RickKessler** [comment]
Try new input
SUBPROCESS_OPTMASK=1 
to write [prefix].FITRES each iteration. I tried testing in
   /project2/rkessler/SURVEYS/DES/USERS/djbrout/dustdriver
but RUNTEST_SUBPROCESS_SIM seems to be broken.

**Comment by bap37** [comment]
I have fixed RUNTEST_SUBPROCESS_SIM - it will now reproduce the segfault error. Iteration 0 is the expected number

**Comment by RickKessler** [comment]
Fixed. 
A while back I had suppressed muerr_renorm() function for SUBPROCESS to avoid memory leak from repeated malloc after each iteration, and since SUBPROCESS doesn't need muerr_renorm. More recently I added an OPTMASK flag to write out the FITRES file each iteration ... which includes muerr_renorm. It was crashing on trying to write muerr_renorm that had not been malloced or filled. Fix is to bypass writing muerr_renorm for SUBPROCESS.
