### ISSUE TITLE
CID overflow in simulation stage

### ISSUE THREAD

**Issue by pmacias** [RickKessler/SNANA#599]
Hi Rick,

I noticed something strange going on with CIDs going to 0, -1, then very large numbers which caused stage 1 SIM to crash.

Output is here:

/scratch/midway2/rkessler/PIPPIN_OUTPUT/WFIRST_STARTERKIT+RUBIN/1_SIM/WFIRST_SIMDATA_G10/LOGS/FAIL_SUMMARY.LOG

Thanks!
-Phil

**Comment by RickKessler** [comment]
The problem is that NGEN_SEASON results in NGENTOT_LC being x10 larger than the number of allocated random CIDs. Sim is now modified to abort if both NGENTOT_LC>0and NGEN_SEASON>0;
FATAL ERROR ABORT called by init_DNDZ_Rate
   Cannot have both NGENTOT_LC>0 and NGEN_SEASON>0
   At least one must be set to zero.
