### ISSUE TITLE
init_CIDRAN error

### ISSUE THREAD

**Issue by hombit** [RickKessler/SNANA#641]
My batch jobs exit with the following error
```text
SIMLOGS_LSST_WFD/TMP_kost_LSST_WFD_MODEL66_Mdwarf_NONIaMODEL0-0040_23925.LOG <==
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by init_CIDRAN
   NSTORE_ALL=2111500 exceeds bound of CIDRAN_MAX = 1140000
   NSTORE_ALL= 1111500(CIDOFF) + 0(NGEN_LC) + 1000000(NGENTOT_LC)
```

My INPUT file is at `/global/cfs/cdirs/snana/SURVEYS/LSST/ROOT/PLASTICC_DEV/survey_config/SIMGEN_MASTER_LSST_WFD_MDWARF.INPUT` on Cori

**Comment by RickKessler** [comment]
ABORT is caused by conflicting inputs (NGEN_UNIT & NGENTOT_LC) that were not caught. Fixed submit_batch to now abort with
FATAL ERROR ABORT : 
   Cannot mix NGEN_UNIT and NGENTOT_LC in
   SIMGEN_MASTER_LSST_WFD_MDWARF.INPUT .
   Either remove NGENTOT_LC from GENOPT[_GLOBAL]
   or remove NGEN_UNIT from CONFIG.
