### ISSUE TITLE
NSPLITRAN option crashes BBC

### ISSUE THREAD

**Issue by jpierel14** [RickKessler/SNANA#69]
Adding NSPLITRAN option causes a (seemingly) unrelated crash. Relevant command is:

`SALT2mu_fit.pl $WFIRST_ROOT/SALT3/examples/wfirst/pipeline/WFIRST_BBC.input NSPLITRAN 10`

**Comment by RickKessler** [comment]
The error is 
 FATAL ERROR ABORT : 
	 Unable to find argument of 
	 file=SALT2mu_SHALLOW+MEDIUM+DEEP/DMS/FITOPT000.FITRES
 
so you need to be in the same directory as the input FITRES  file, or provide full path of in input file. Note that INPDIR keys are ignored for NSPLITRAN, so it uses file= argument.
Please note the comments at top of SALT2mu_fit.pl:
# NSPLITRAN=<n> argument operates on the native file=<file> argument 
# in the SALT2mu-input file, and ignores the supplmental batch keys 
# INPDIR, INPDIR+,  and MUOPT. Batch keys NODELIST, BATCH_INFO and 
# SNANA_LOGIN_SETUP are used. If NSPLITRAN=<n> appears inside the 
# SALT2mu-input file, this is equivalent to the command-line specifier; 
# command-line NSPLITRAN=<n> overrides value in SALT2mu-input file. 
# The NSPLITRAN mode creates an output sub-directory with a specific 
# name, "OUT_SALT2mu_NSPLITRAN[n]", and can be changed using the 
# "OUTDIR_OVERRIDE: <OUTDIR>"  key. The output file names are hard-wired 
# with prefix=OUT_TEST. Note that for <n> split jobs, <n+1> batch jobs
# are submitted because the n+1'th job reads back all of the previous
# output and prepares a summary of averages and RMS in OUT_TEST_summary.out.
#
