### ISSUE TITLE
Cannot use nml to output appropriate files for re-training SALT2 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#711]
This behaviour can be replicated here by running the following command in its directory:

/project2/rkessler/PRODUCTS/SNANA_DEBUG/SALT2-RETRAIN/RUNME 
```

 FATAL ERROR ABORT called by get_PARSE_WORD
   iwd=1 exceeds NWD_STORE=1
   Check '@INSTRUMENT' 


Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
```

A version of this file without the relevant SALT2 retraining key can be run by doing 

/project2/rkessler/PRODUCTS/SNANA_DEBUG/SALT2-RETRAIN/REG_RUNME - this does not crash

**Comment by RickKessler** [comment]
First of all, translating format is an "snana.exe" job, not something that runs with LC fitting; e.g., 

snana.exe NOFILE \
  VERSION_PHOTOMETRY  PIP_P21-BEST_SIMSNLS_4D_BS20-BEST \
  OPT_REFORMAT_SALT2 2 \
  REFORMAT_KEYS  '@INSTRUMENT SLOAN @MAGSYS AB'

I fixed snana to read OPT_REFORMAT_SALT2 and REFORMAT_KEYS from command line, but there are problems in the translate code that hasn't been used since 2014.
