### ISSUE TITLE
SALT2beta bug again

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#715]
As per zoom discussion, checking GENPDF/asymGauss for SALT2beta overrides doesn't work, resulting in the following errors:

/scratch/midway2/rkessler/PIPPIN_OUTPUT/P21-SYS/1_SIM/SIMPS1_4D_BS20-BEST/LOGS/FAIL_SUMMARY.LOG

I believe SNANA needs to be told the acceptable number of times to be able to read the SALT2beta key?

**Comment by RickKessler** [comment]
reading GENPDF_FILE had set a flag that it was read from a file, so the SALT2BETA in sim-input (from file) and SALT2BETA from genpdf_file were both flagged as "from file" and thus could not assign priority. It is now fixed so that command line GENPDF_FILE argument is flagged "command line arg" (not 'from file')  so that it has priority over keys in the sim-input file.
