### ISSUE TITLE
snlc_sim stuck writing lightcurves

### ISSUE THREAD

**Issue by rmorgan10** [RickKessler/SNANA#731]
When running snlc_sim.exe for SN-Ia lightcurves, the simulation gets stuck while writing the first light curve. We're also using NGENTOT_LC instead of NGEN_LC, so I don't think it's cuts that are causing the program to hang.

Here is a quick way to reproduce the error (at FNAL):
- `cd /data/des40.a/data/nsherman/DESFollowup_Testing/DES_Followups_w_Tristan/`
- `source setup_commands.sh`
- `cd events/GW190510`
- `snlc_sim.exe SIMGEN_DES_SALT2.input`

We haven't changed our code or input files, so we think some there may have been some SNANA changes we haven't accounted for. Would you mind taking a look and letting me know if you can spot why the simulation gets stuck indefinitely?

**Comment by RickKessler** [comment]
this is indeed a strange bug. Short-term solution is to remove the blank line above the DOCUMENTATION key in the SIMLIB file. This blank line somehow causes the reader to never recognize the end-of-file and to interpret EOF as a blank line; hence the infinite loop. I copied the input files to my own debug directory (~/snana_debug/SIMLIB_DOCANA_BUG), and I will try to fix this later so that blank lines at the top of SIMLIB don't matter.

**Comment by rmorgan10** [comment]
Wow that is very weird. Thanks for looking into it!

**Comment by RickKessler** [comment]
Finally fixed evil bug that was causing infinite loop when first SIMLIB line is blank.
