### ISSUE TITLE
wfit systematics giving inconsistent results when run in "fast" and "slow" mode

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#754]
I’ve been comparing results from wfit before and after the implementation of the faster method of handling large cov matrices. I see some large discrepancies between the outputs using the old and slower (>20mins) wfit code and the newest and fastest (~6min) code.

I put the results here:
`$PIPPIN_OUTPUT/DES5YR_5YRBC_UB/8_WFIT` is the output I run yesterday (faster version of the code),
and `$PIPPIN_OUTPUT/DES5YR_5YRBC_UB/8_WFIT_slow` is the output I run a week ago (slower version of the code).

**Comment by RickKessler** [comment]
Looks like I messed up the original slow-vs-fast test; indeed there are notable differences. I increased the 10 sigma chi2-diag cut to 30 sigma, and the slow-vs-fast agreement is much better. For 44 wfits, 36 have identical results and the remaining 8 differ only in the last decimal. The speed up is now a factor of 2.6 instead of >3, but still useful. See slack for a few more details.

**Comment by RickKessler** [comment]
Forgot to mention that there is a new wfit input to disable the speed trick
  wfit.exe <inputHD>  -speed_flag_chi2 0
