### ISSUE TITLE
FATAL ERROR ABORT called by malloc_FLUXTABLE_SEDMODEL

### ISSUE THREAD

**Issue by anaismoller** [RickKessler/SNANA#759]
It seems that there was an update with SNANA and now the NonIa models break....  I used these configuration some months ago and it worked perfectly.

Configuration:
$PIPPIN/configs/am/AM_DES5YR_SIMS_TEST.yml

Error:
FATAL ERROR ABORT called by malloc_FLUXTABLE_SEDMODEL

thanks!

**Comment by RickKessler** [comment]
I think the problem is using out-dated SIMSED model in Maria's directory. Should use the models in 
$PLASTICC_ROOT/model_libs
$PLASTICC_ROOT/model_libs_updates

I re-ran SNIax using
   $PIPPIN_OUTPUT/AM_DES5YR_SIMS_TEST/1_SIM/5XDES/LOGS/RICK.CMD
and it runs OK. I had to re-make the SIMSED-binary, and we will need to do the same for 91bg.
Note that I started another issue to write a script which prepares the SIMSED-binaries.
