### ISSUE TITLE
Flat x1,c simulation generation

### ISSUE THREAD

**Issue by anaismoller** [RickKessler/SNANA#76]
According to SNANA manual, when ignoring GENSIGMA_c and GENSIGMA_x1 it will generate a flat distribution in c and x1 respectively. But, when this is done I don't get flat distributions. How can we generate flat color and stretch simulation distributions? I have copied my input file in $SNANA_DEBUG/Anais

**Comment by RickKessler** [comment]
Are you looking at manual section "4.7.3 SIMLIB Options for each LIBID" ? If so, these instructions are for SALT2 parameters in the SIMLIB header. For nominal generation using sim-input keys, GENSIGMA must be x10 greater than the range to generate a flat distribution. For example, "GENSIGMA_SALT2c: 1E6 1E6" generates a flat distribution. To examine generated distributions, use SIMGEN_DUMPALL option, otherwise you will see the ACCEPTED distribution after trigger.

**Comment by anaismoller** [comment]
I still don't get the SNANA manual comment but I do get the flat distribution with large GENSIGMA which can be seen in the DUMPALL output. Thanks!
