### ISSUE TITLE
zHD from BBC does not reflect host galaxy confusion

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#778]
https://darkenergysurvey.slack.com/archives/DPLPJ1J9Y/p1642107825001600

**Comment by RickKessler** [comment]
Finally found the problem. For the original WRONGHOST_FILE model using a map, the final redshift was indeed modified to reflect a wrong host match. When the HOSTLIB+NBR feature was added later, I forgot to update reported redshift. Fixed code so that either WRONG-HOST model results in incorrect final redshift.
