### ISSUE TITLE
Divide by zero error

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#818]
Main pippin directory: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/BV_FR_LAMBDACDM`
File with error: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/BV_FR_LAMBDACDM/6_BIASCOR/BCOR_OMPRI/output/SCRIPTS_BBCFIT/CPU0004_JOBLIST_midway2-login1.LOG`
Error:
```
 f_some_fail     = float(n_some_fail)/float(n_all)
 ZeroDivisionError: float division by zero
```

**Comment by RickKessler** [comment]
For job 064 the FITRES file has no entries even though the SALT2mu log file says that 181 events were written to the FITRES file. May have been a file system glitch at the moment this file was written. I re-ran BBC for job 64, and it works fine to create a FITRES file, so the problem is not reproducible.

**Comment by OmegaLambda1998** [comment]
Seemed to be a temporary glitch. Resolved on a rerun, closing.
