### ISSUE TITLE
All BBC runs failing due to "All DATA events fail cuts"

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#820]
Pippin outputs: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/BV_V_1D_FIXED_OM` and `/scratch/midway2/rkessler/PIPPIN_OUTPUT/BV_V_1D_FIXED_W0`
Both of these have a number of different BBC tasks which act on 75 simulations. Every single BBC task across both pippin outputs has the same failure:
```
  FAILURE-0001:
  JOB_LOG_FILE:       PIP_BV_V_1D_FIXED_W0_DESSIM_w_n1_0_om_0_3-0001_FITOPT000_MUOPT000.LOG
  FAIL_REPEAT_SCRIPT: 
      FAIL_REPEAT_PIP_BV_V_1D_FIXED_W0_DESSIM_w_n1_0_om_0_3-0001_FITOPT000_MUOPT000.CMD
  FAIL_MODE:          ABORT
  ABORT_MESSAGES:
     - FATAL ERROR ABORT called by read_data
     - All DATA events fail cuts
     - Check cut-windows in SALT2mu input file.
```
Obviously with different `JOB_LOG_FILE` and `FAIL_REPEAT_SCRIPT` for each BBC task

**Comment by RickKessler** [comment]
First, I fixed the abort to include a cut-summary dump which shows that all events fail LOGMASS because all LOGMASS values are -9999 and default cut-window is -20 to 20. Short-term fix is to open cut window with
logmass_min=-1.0E4

The bigger problem was that there is no LOGMASS info and a bug caused the -9999 values to appear in the FITRES file. This bug is fixed, so next time snlc_fit runs, the HOST_LOGMASS column won't appear.
