### ISSUE TITLE
Absurdly Small errors in BBC-fitted parameters

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#955]
Debug output in `$SNANA_DEBUG/BBC_crazyErrors`

**Comment by RickKessler** [comment]
For the debug example, I changed p2=3.1 to 3.11 (beta) and this fixed the problem. Next I will try to add a trap for crazy-small errors and automatically re-run the fit with small p2 perturbation.

**Comment by RickKessler** [comment]
after SALT2mu/BBC  fit, new function "crazy_small_errors" checks if the M0 errors are well below 0.1/sqrt(NEVT_z), which should be the min error floor. If at least 3 M0-errors are below 1/2 the min-error-floor, the entire fit is repeated with input alpha += 0.001 and input beta += 0.01. Also added NWARN_CRAZYERR to output YAML so that submit_batch can take action (later), and added crazy-err warnings at top of output FITRES files.

Here is an example where TEST0 is original fit with crazy-small errors, and TEST2 is the result of an auto-repeated fit with initial alpha, beta perturbed:

TEST0.FITRES:#  alpha0         =    0.13894 +-  0.00003   
TEST2.FITRES:#  alpha0         =    0.13900 +-  0.00473   
 
TEST0.FITRES:#  beta0          =    2.99465 +-  0.00023   
TEST2.FITRES:#  beta0          =    2.99544 +-  0.05093   
 
TEST0.FITRES:#  m0_00-<M0avg>  =    0.00335 +-  0.00071  
TEST2.FITRES:#  m0_00-<M0avg>  =    0.00332 +-  0.01170 
 
TEST0.FITRES:#  m0_01-<M0avg>  =    0.01019 +-  0.00069 
TEST2.FITRES:#  m0_01-<M0avg>  =    0.01019 +-  0.01122  
 
TEST0.FITRES:#  m0_19-<M0avg>  =   -0.20114 +-  0.00882   TEST2.FITRES:#  m0_19-<M0avg>  =   -0.20118 +-  0.15170

**Comment by RickKessler** [comment]
I re-ran BBC on 50 samples + 10 syst after releasing the auto-detect for crazy errors, and found 3 examples:

zgrep -i crazy OUTPUT_BBCFIT-00*/FITOPT0*.FITRES.gz
OUTPUT_BBCFIT-0027/FITOPT009_MUOPT000.FITRES.gz:# WARNING(MINOR): 16 fit M0ERR had crazy values --> fit repeated.
OUTPUT_BBCFIT-0046/FITOPT000_MUOPT000.FITRES.gz:# WARNING(MINOR): 20 fit M0ERR had crazy values --> fit repeated.
OUTPUT_BBCFIT-0046/FITOPT007_MUOPT000.FITRES.gz:# WARNING(MINOR): 20 fit M0ERR had crazy values --> fit repeated.

The repeated fit values look sensible by eye … and clearly way more sensible than the crazy errors from the first fit attempt that resulted in w=-1.5 for sample 0046. These warnings are flagged as MINOR. If crazy small errors persist after 2nd fit attempt, the warning message is SEVERE and non-zero NWARN_CRAZYERR is written to YAML output.

My hunch is that this crazy-error feature has been unknowingly causing problems in previous many-sample tests since there was no clear way to flag it other than MUERR_RENORM/MUERR << 1 (opposite of too-big MUERR_RENORM issue posted yesterday on git issue)
