### ISSUE TITLE
unknown crash in biascor simulations

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#983]
log with crash here `/scratch/midway2/rkessler/PIPPIN_OUTPUT/HELEN_HOSTNBR_WITH_CC/1_SIM/DESBIASCOR_IA/LOGS/TMP_hele_PIP_HELEN_HOSTNBR_WITH_CC_DESBIASCOR_IA_SNIaMODEL0-0009_52593.LOG`

**Comment by RickKessler** [comment]
The abort message tried to access the neighbor list, but since this HOSTLIB does not have +HOSTNBR it crashed accessing non-existent memory. I fixed the abort message so now you have

<img width="589" alt="fixed_abort_message" src="https://user-images.githubusercontent.com/24592476/185813758-fa650c22-7ba9-4c75-9785-da141336e309.png">

which complains about absurdly large separation. The Sersic params for this galaxy are
  GALID   ZTRUE  a0_Sersic  b0_Sersic  n0_Sersic
4300983521  0.10896  27.168308    2.33805   8.288839

so I suggest rejecting such events from the HOSTLIB.
